### ISSUE TITLE
Feature request: Use MultiZip to zip mutable iterators with immutable iterators.

### ISSUE THREAD

**Issue by nielsle** [rayon-rs/rayon#1004]
It could be nice to be able to use MultiZip to zip a combination of mutable and immutable iterators.

As far as I can see itertools supports this. Here is the [itertools version](https://docs.rs/itertools/latest/itertools/fn.multizip.html)
~~~ rust
let mut results = [0, 0, 0, 0];
let inputs = [3, 7, 9, 6];

for (r, index, input) in multizip((&mut results, 0..10, &inputs)) {
    *r = index * 10 + input;
}
~~~
See also https://github.com/rayon-rs/rayon/issues/567

**Comment by cuviper** [comment]
Did you try `(&mut results, 0..10, &inputs).into_par_iter()`?

**Comment by nielsle** [comment]
Ah, you are right. 

Sorry about the noise, and that you for making Rayon.
