### ISSUE TITLE
[FYI] Updated "Wiki -> Guide-to-Development" page with info on how to install Nightly compiler

### ISSUE THREAD

**Issue by jimkring** [rayon-rs/rayon#1007]
This is just an FYI to the project team.

On the [Wiki -> Guide-to-Development](https://github.com/rayon-rs/rayon/wiki/Guide-to-Development) page I added a note about how to install rust "Nightly" compiler, since that is required for running benchmarks and examples.

![image](https://user-images.githubusercontent.com/381432/211625591-ecf99e34-f9c5-47da-8789-60bebcaa4e14.png)

I had to search for how to do this, so I figured a note might save others the trouble, too.

Thanks!

**Comment by cuviper** [comment]
Thanks for your contribution!

We should update that further though, because nowadays nightly is only required for `cargo bench`. We could even migrate that to something stable like criterion, but that's a big task. (which I've started and dropped a few times...)

**Comment by cuviper** [comment]
I updated that to reflect stable, but feel free to wiki-edit further if it reads unclearly.

**Comment by jimkring** [comment]
Thanks! Looks good 👍🏻
