### ISSUE TITLE
Wait until par_iter is done

### ISSUE THREAD

**Issue by romancardenas** [rayon-rs/rayon#1015]
I'm new to rayon, and I wanted to know if there is any way to make sure that a `par_iter` iterator is done before continuing with the execution. Let's assume we have something like this:
```rust
x.par_iter().for_each(|_| { whatever});
y.par_iter().for_each(|_| { whatever});
```
And I want to make sure that rayon does not start executing the second iterator until is done with the first. Any suggestion?

**Comment by wagnerf42** [comment]
hi, it is already the case. the first for_each will wait for its completion before continuing with the next code line.

**Comment by romancardenas** [comment]
Great, thanks! Then my bug is somewhere else hahaha
