### ISSUE TITLE
Feature request: Add the ability to limit the total number of tasks

### ISSUE THREAD

**Issue by gootorov** [rayon-rs/rayon#1020]
In my use case tasks arrive unconditionally. If there are more tasks coming in than the pool can handle, it may be possible to consume all of the available memory.

This is an exaggerated example, but consider the following:
```Rust
fn main() {
    let pool = rayon::ThreadPoolBuilder::new().build().unwrap();

    loop {
        pool.spawn(move || loop {})
    }
}
```
This consumes all of the available memory until the program is terminated by an OOM handler.

It is possible to work around this, but it would be really great if it were possible to set a total upper limit of tasks, and have a fallible API, where `spawn` would fail if there is no more room in the queues.

**Comment by cuviper** [comment]
There's no return value from `spawn` -- would you want it to panic if your limit is exceeded?

Regardless, there's no global accounting of active or queued tasks. I think this would be better managed from the outside, in your code that's queuing tasks, where you can apply a rate limiter or take whatever recovery action makes sense in your domain.

**Comment by gootorov** [comment]
Would it be possible to add such an accounting system and have just a method(s) that returns the number active or queued tasks? Then, a user could decide whether to queue more or not. That's kind of what I do currently , but I thought something like this may be useful to have within the library.

Though, I guess such an API would be somewhat racy, which is another issue...

**Comment by cuviper** [comment]
I'm loath to track active tasks, because we would have to add new counters that impact everyone's performance. We could possibly report queued tasks by polling the queues for each thread, and this would definitely be racy, but the advantage is that this wouldn't add overhead to users that don't need it. Even then, we can only do it because `crossbeam-deque` supports `len()`, but it hasn't always had that, so we would have to hope that new versions never remove it.

**Comment by cuviper** [comment]
Also, this granularity might not actually be useful to you, as it would include all the dynamic job splitting that happens within parallel iterators, for example. If you only want to count your `spawn`s, better to do that yourself.

**Comment by gootorov** [comment]
That makes sense. I'll stick to outside management then. Thank you for detailed responses!
