### ISSUE TITLE
Antivirus flagging rayon core

### ISSUE THREAD

**Issue by willmendil** [rayon-rs/rayon#1035]
Hi, this is more of an FYI, that issue, but i can see how it might become a problem.

Bitdefender is flagging rayon-core. This has already been posted in https://github.com/rayon-rs/rayon/issues/980
but it was closed, though not fixed.

These are the flagged files in my case, they are files produced when building the code.

```
[REDACTED]\target\debug\build\rayon-core-aeb3348f58dd0399\build_script_build-aeb3348f58dd0399.exe    -    Gen:Suspicious.Cloud.4.juW@aSpmOgj    -    No action was taken 
[REDACTED]\target\release\build\rayon-core-003a327c101bad65\build-script-build.exe    -    Gen:Suspicious.Cloud.4.juW@aqN!W2k    -    No action was taken 
```

**Comment by cuviper** [comment]
The build script barely does anything at all:
https://github.com/rayon-rs/rayon/blob/master/rayon-core/build.rs

Either your compiler or standard library are compromised, or your antivirus is giving a false report, and I would bet on the latter.

**Comment by hgi0100** [comment]
Same problem here, build-script-build.exe is infected with Gen:Suspicious.Cloud.4.kuW@aWEOZS

**Comment by RoDmitry** [comment]
Same with Kaspersky: build-script-build.exe VHO:Trojan.Win32.Sdum.gen
Earlier it was not flagging it. It started after I updated Rust to 1.68

**Comment by hgi0100** [comment]
Yes my problem started after I updated rust to 1.68 too

**Comment by hgi0100** [comment]
checked with another antivirus and today got Gen:Variant.Tedy.319128

**Comment by cuviper** [comment]
I'm afraid there's nothing actionable on the rayon side. I already linked the code here in the repo, but you can also see on docs.rs that the published crate does not do anything bad, only prints a single string:
https://docs.rs/crate/rayon-core/1.11.0/source/build.rs

I suggest contacting your antivirus vendors with your sample binaries, and hopefully they can tune their heuristics to avoid flagging these -- or explain what virus they think they've really found.
