### ISSUE TITLE
Document performance characteristic under small collection sizes

### ISSUE THREAD

**Issue by ZhennanWu** [rayon-rs/rayon#1044]
# Problem
Rayon performance characteristic is very unexpected when collection size become smaller

For a medium-sized work unit (simulated by 30 random uncached memory reads). We can see a multi-threaded rayon actually performs faster on 2000 elements than on 50 elements.
![image](https://user-images.githubusercontent.com/38578020/236578432-5e288797-7ff0-4a27-a991-046c370b0a14.png)

For a very expensive work unit (simulated by 3000 random uncached memory reads). We can see multi-threaded rayon is sigfinicantly slower (50% more execution time) than `std::thread::scope` before reaching cpu thread count. This is not expected even if we take synchronization overhead into account.
![image](https://user-images.githubusercontent.com/38578020/236580164-3a60c8fa-add1-4fd5-9671-41bb0c092632.png)

This is a separate problem from whether each element is assumed expensive/cheap. Split length mechanism will not help this situation. Presumably, split length mechanism could even introduce this problem to larger collections.

This perf characteristic is confusing and unexpected of a normal threadpool. It has two indications:
1. It should be warned if people have a medium/cheap work units with very unpredictable lengths. A single short data incidence could be much more expensive than a long data.
2. Rayon should not be used as a handy wrapper to `std::thread` or openmp mimics, if there are not too many parallelism/workers to begin with.

If it is intentional, it deserves documentation.

# Step to reproduce
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=224f14acf9f547d8ee7def6e0114224c

(Dependencies: rayon, tokio, paste)

The code works in following logic:
1. Spawn `$N_PAR` number of work units
3. Each work unit performs `$N_MEM_READ` random uncached memory read from a 800MB usize array.
4. (To avoid extra interference, the pseudorandom index is generated by a multiplicative group with a multiplicative order over 16M. That is, it will generate 16M non-overlapping pseudorandoms before looping back.)
5. Each work unit only captures a `usize` seed from main thread for random index generation. The synchronization overhead for them should be miniscule.

# System Configuration
Intel 12700k with big cores only (8c16t). Operating system: WSL2.

**Comment by cuviper** [comment]
> Operating system: WSL2

Can you please try with either native Linux or native Windows?

> For a medium-sized work unit (simulated by 30 random uncached memory reads). We can see a multi-threaded rayon actually performs faster on 2000 elements than on 50 elements.

On my AMD Ryzen 7 5800X (also 8c16t), running native Fedora 38, `par_iter_medium` look reasonable -- noisy at the low end and then scaling pretty well. I definitely do not see your effect of 50 being slower than 2000!

```
test bench::rayon_par_iter_medium_1             ... bench:       2,430 ns/iter (+/- 32)
test bench::rayon_par_iter_medium_2             ... bench:       8,905 ns/iter (+/- 1,288)
test bench::rayon_par_iter_medium_3             ... bench:      10,152 ns/iter (+/- 3,162)
test bench::rayon_par_iter_medium_4             ... bench:      11,282 ns/iter (+/- 3,417)
test bench::rayon_par_iter_medium_5             ... bench:      10,434 ns/iter (+/- 1,806)
test bench::rayon_par_iter_medium_6             ... bench:      11,875 ns/iter (+/- 4,326)
test bench::rayon_par_iter_medium_7             ... bench:      11,421 ns/iter (+/- 3,441)
test bench::rayon_par_iter_medium_8             ... bench:       9,814 ns/iter (+/- 3,331)
test bench::rayon_par_iter_medium_9             ... bench:      10,587 ns/iter (+/- 3,938)
test bench::rayon_par_iter_medium_10            ... bench:      10,369 ns/iter (+/- 3,604)
test bench::rayon_par_iter_medium_20            ... bench:      13,411 ns/iter (+/- 1,122)
test bench::rayon_par_iter_medium_50            ... bench:      21,101 ns/iter (+/- 2,440)
test bench::rayon_par_iter_medium_100           ... bench:      32,405 ns/iter (+/- 1,852)
test bench::rayon_par_iter_medium_200           ... bench:      54,983 ns/iter (+/- 3,250)
test bench::rayon_par_iter_medium_500           ... bench:     117,920 ns/iter (+/- 6,078)
test bench::rayon_par_iter_medium_1000          ... bench:     222,385 ns/iter (+/- 42,546)
test bench::rayon_par_iter_medium_2000          ... bench:     407,368 ns/iter (+/- 29,240)
test bench::rayon_par_iter_medium_5000          ... bench:     927,949 ns/iter (+/- 46,044)
test bench::rayon_par_iter_medium_10000         ... bench:   1,820,066 ns/iter (+/- 69,031)
```

> For a very expensive work unit (simulated by 3000 random uncached memory reads). We can see multi-threaded rayon is sigfinicantly slower (50% more execution time) than `std::thread::scope` before reaching cpu thread count.

Here's a sample that I get -- with kudos to tokio, but rayon still beat `std::scope`:

```
test bench::rayon_par_iter_heavy_10             ... bench:     376,895 ns/iter (+/- 24,591)
test bench::rayon_par_iter_thread1_heavy_10     ... bench:     372,254 ns/iter (+/- 22,900)
test bench::rayon_spawn_heavy_10                ... bench:     358,735 ns/iter (+/- 19,737)
test bench::rayon_spawn_thread1_heavy_10        ... bench:   2,747,268 ns/iter (+/- 71,716)
test bench::serial_heavy_10                     ... bench:   2,702,601 ns/iter (+/- 45,815)
test bench::std_thread_scope_heavy_10           ... bench:     416,850 ns/iter (+/- 13,930)
test bench::tokio_spawn_heavy_10                ... bench:     342,417 ns/iter (+/- 6,469)
```

BTW, you didn't plot data for `par_iter_thread1`, but you have a bug that you're not actually running that workload in the local `pool` you created, so it's still running in the global pool. That ought to be closer to the serial number.

> If it is intentional, it deserves documentation.

It's not intentional, especially given that I can't reproduce your results. I suspect there's a bad interaction with WSL causing sleeping threads to be slower to wake up, but that's just a wild guess.

**Comment by ZhennanWu** [comment]
@cuviper Well I would have never suspected WSL2 could have such a dramatic impact. I was consistently troubled by this problem on WSL2.

After testing on more platforms, it does appear to be a WSL2 specific issue.

## On native Win11, Intel 12700k 8c16t
Relevant results are
```
test bench::rayon_par_iter_medium_1            ... bench:       1,514 ns/iter (+/- 203)
test bench::rayon_par_iter_medium_2            ... bench:      16,665 ns/iter (+/- 962)
test bench::rayon_par_iter_medium_3            ... bench:      21,259 ns/iter (+/- 978)
test bench::rayon_par_iter_medium_4            ... bench:      11,779 ns/iter (+/- 563)
test bench::rayon_par_iter_medium_5            ... bench:      11,309 ns/iter (+/- 815)
test bench::rayon_par_iter_medium_6            ... bench:      10,448 ns/iter (+/- 1,171)
test bench::rayon_par_iter_medium_7            ... bench:      10,012 ns/iter (+/- 966)
test bench::rayon_par_iter_medium_8            ... bench:       9,832 ns/iter (+/- 1,183)
test bench::rayon_par_iter_medium_9            ... bench:      10,101 ns/iter (+/- 1,911)
test bench::rayon_par_iter_medium_10           ... bench:      10,705 ns/iter (+/- 3,263)
test bench::rayon_par_iter_medium_20           ... bench:      13,078 ns/iter (+/- 1,883)
test bench::rayon_par_iter_medium_50           ... bench:      18,637 ns/iter (+/- 1,269)
test bench::rayon_par_iter_medium_100          ... bench:      31,377 ns/iter (+/- 6,575)
test bench::rayon_par_iter_medium_200          ... bench:      49,082 ns/iter (+/- 7,082)
test bench::rayon_par_iter_medium_500          ... bench:     101,683 ns/iter (+/- 4,256)
test bench::rayon_par_iter_medium_1000         ... bench:     196,048 ns/iter (+/- 19,077)
test bench::rayon_par_iter_medium_2000         ... bench:     339,868 ns/iter (+/- 19,647)
```
It overshoot a little bit more in the start, but nothing as serious as my initial report.
```
test bench::rayon_par_iter_heavy_10            ... bench:     315,435 ns/iter (+/- 24,443)
test bench::rayon_spawn_heavy_10               ... bench:     321,813 ns/iter (+/- 15,410)
test bench::serial_heavy_10                    ... bench:   2,802,680 ns/iter (+/- 200,120)
test bench::std_thread_scope_heavy_10          ... bench:     599,721 ns/iter (+/- 38,095)
test bench::tokio_spawn_heavy_10               ... bench:     628,040 ns/iter (+/- 240,969)
```
It matches your results on native Fedora

## On VMWare Workstation Player Ubuntu 22.04.02, Intel 12700k 8c16t, 16 logical cpu.
Everything is extremely slow, if an anomaly does exist it would be covered up by the lag.

However, rayon did managed to beat `std::thread::scope`
```
test bench::rayon_par_iter_heavy_10      ... bench:     724,460 ns/iter (+/- 129,325)
test bench::rayon_spawn_heavy_10         ... bench:     703,517 ns/iter (+/- 97,666)
test bench::std_thread_scope_heavy_10    ... bench:     799,780 ns/iter (+/- 201,911)
test bench::tokio_spawn_heavy_10         ... bench:     971,798 ns/iter (+/- 739,294)
```

I don't immediately have a native Linux to experiment on. But I think this is indeed a WSL2 specific issue. Closing.

**Comment by ZhennanWu** [comment]
Well I guess there is no harm to post the full data in case anyone else is curious about the real perf characterstics. Different platform do have small differences but not much.

## Native Windows 11. Medium-sized work units
![image](https://user-images.githubusercontent.com/38578020/236661702-1e5fe05b-8b9d-460f-a703-8b25e4cec003.png)

## Native Windows 11. Expensive work units
![image](https://user-images.githubusercontent.com/38578020/236661712-24d7fe8f-75cb-43e3-8212-394adea1ff09.png)

## Native Gentoo Linux. Medium-sized work units
![image](https://user-images.githubusercontent.com/38578020/236661744-956934bf-4fbb-4dfa-b0a0-488ddb8203ac.png)

## Native Gentoo Linux. Expensive work units
![image](https://user-images.githubusercontent.com/38578020/236661779-987c081d-6885-4721-ae39-47a5b977c70c.png)
