### ISSUE TITLE
Iterating over an N-dimensional range

### ISSUE THREAD

**Issue by davids91** [rayon-rs/rayon#1045]
I have a 3D range ( x,y,z ) and would like to paralellize it. Does the below code make any sense, isn't it ineffective? 

```
use rayon::prelude::*;

let size = 1024;

(0..size).into_par_iter().for_each(|i| {
    (0..size).into_par_iter().for_each(|j| {
        (0..size).into_par_iter().for_each(|k| {
            // Do something with i, j, and k
        });
    });
});
```

I fear because it is 3 different `into_par_iter`-s it will mess with the thread-count, and because of that the effectiveness.

**Comment by adamreichold** [comment]
(Both approaches can also be combined, i.e. merge the outer two loops into a single parallel iterator over two dimensions but the keep the innermost loop sequential.)

**Comment by davids91** [comment]
You are right, if there are e.g. 8 cores, then I wouldn't gain much improvement from 
```
use rayon::prelude::*;

let size = 1024;

(0..size).into_par_iter().for_each(|i| {
    (0..size).into_par_iter().for_each(|j| {
        (0..size).into_par_iter().for_each(|k| {
            // Do something with i, j, and k
        });
    });
});
```
over 
```
use rayon::prelude::*;

let size = 1024;

(0..size).into_par_iter().for_each(|i| {
    (0..size).for_each(|j| {
        (0..size).for_each(|k| {
            // Do something with i, j, and k
        });
    });
});
```

Thank you for the help!
