### ISSUE TITLE
Is wasm-bindgen-rayon actually needed?

### ISSUE THREAD

**Issue by qtfkwk** [rayon-rs/rayon#1047]
Hello! I see [the note](https://github.com/rayon-rs/rayon#usage-with-webassembly)... but I'm able to compile and run with the following (and note... no mention of wasm-bindgen-rayon):

```bash
#!/usr/bin/bash
set -xeo pipefail
PORT=8080
cargo install trunk miniserve
cargo new rayon-wasm-test
cd rayon-wasm-test
touch index.html
cat <<EOF >Cargo.toml
[package]
name = "rayon-wasm-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7.0"
wasm-bindgen = "0.2.85"

[dependencies.web-sys]
version = "0.3.62"
features = [
    "console",
]
EOF
cat <<EOF >src/main.rs
use std::collections::HashMap;
use rayon::prelude::*;
use wasm_bindgen::JsValue;

fn main() -> Result<(), JsValue> {
    let map = HashMap::from([("a", 1), ("b", 2), ("c", 3)]);
    if let Some(b) =
        map
            .par_iter()
            .find_map_any(|(k, v)| if k.starts_with('b') { Some(v) } else { None })
    {
        web_sys::console::log_1(&JsValue::from_str(&format!("b = {b}")));
        // prints "b = 2" to console log
    }
    Ok(())
}
EOF
trunk build
cd dist
miniserve -vp $PORT --index index.html
```

Then surf to <http://localhost:8080>, open developer tools console, and should see "b = 2".

So... I'm wondering... is it falling back to sequential iterators? Or is it in fact using web workers? Or is something else going on? Thanks!

**Comment by cuviper** [comment]
> is it falling back to sequential iterators?

Roughly, yes, since #1019. I suppose we could mention that fallback in the README, but true multi-threading still requires outside help.
