### ISSUE TITLE
[Question] Is `DoubleEndedIterator` needed?

### ISSUE THREAD

**Issue by zommiommy** [rayon-rs/rayon#1053]
Hi, thanks for the library!

I've implemented a few customs parallel iterators for my data structures by manually implementing `Producer` and `UnidexedProducer` myself.

Usually, the hard part of doing so is to implement `DoubleEndedIterator`. 
I've quickly looked at the code in the library, and I don't see many usages except for some skip last in `fold_splits`.

What are the reasons it's required in the associated type `IntoIter` of the `Producer` trait?
Is it possible to remove this constraint from `Producer` and add a `DobuleEndedProducer` trait needed to implement an `IndexedDoubleEndedParallelIterator`?

Thank you

**Comment by cuviper** [comment]
The main reason is that `IndexedParallelIterator::rev` needs it, and the associated producers are too hidden to allow us to just have an extra constraint on that method alone. Maybe we could have split `IndexedDoubleEndedParallelIterator` as you suggest, but IIRC the feeling was that producers that can be arbitrarily split and indexed will probably be trivially reversed true. Do you have an example that makes this particularly difficult?

Often, my suggestion for a custom parallel iterator is to write it as a wrapper over existing impls, at as high a level as you can to avoid the "gory" details. The nature of `drive` and `with_producer` makes it a little easier to do that without exposing any of that relationship in your own API.

> Is it possible to remove this constraint from `Producer`

It would definitely be a semver-breaking change, at least.

**Comment by zommiommy** [comment]
Got it!

A common use case I have is to iterate in parallel over the bits set to 1 in a bitmap.
Usually, with some index built on top of it to allow the split and selects in constant time.

To quickly iter over the ones, I usually read a word into my struct, and find the index of the one using a `trailing_zeros`, and then clear that bit with `word & (word - 1)`.

To have the same performance on `next_back`, I do the same with the word from the end.
Most corner cases arise when the start and the end are within the same word of memory.

Here's an example from an old repo of mine: https://github.com/zommiommy/elias_fano_rust/blob/master/src/simple_select/iter_double_ended.rs

Yeah, this would definitely be a breaking change. This question was mostly out of curiosity about the design than an "issue".

Thank you for your answer!
