### ISSUE TITLE
par_bridge and IndexedParallelIterator

### ISSUE THREAD

**Issue by v1gnesh** [rayon-rs/rayon#1079]
The `ParallellBridge` trait says - [Conversion trait to convert an Iterator to a ParallelIterator](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelBridge.html).

Since the original iterator is sequential, is it an option for `par_bridge` to produce an `IndexedParallelIterator`?
This would allow the use of `collect_into_vec`, which as the doc says, is more memory efficient.

**Comment by cuviper** [comment]
Sorry, no -- `IndexedParallelIterator` almost more like a "random access" iterator. The API requires that it knows exactly how many items it will have, and that we can split it at any index in that range.

**Comment by v1gnesh** [comment]
Okay, thanks for responding. I'll close this off then.

**Comment by v1gnesh** [comment]
Okay, thanks for responding. I'll close this off then.
