### ISSUE TITLE
Feature Request: par_enumerate()

### ISSUE THREAD

**Issue by eliasjonsson023** [rayon-rs/rayon#1080]
Will there, by any chance, be a par_enumerate() in the future?

**Comment by adamreichold** [comment]
Isn't [`IndexedParallelIterator::enumerate`](https://docs.rs/rayon/latest/rayon/iter/trait.IndexedParallelIterator.html#method.enumerate) what you need? Or is your initial parallel iterator not indexed?

**Comment by eliasjonsson023** [comment]
Of course, you are right. I close this issue now.

**Comment by eliasjonsson023** [comment]
not needed

**Comment by eliasjonsson023** [comment]
not needed
