### ISSUE TITLE
rayon_wasm : "Operation not supported on this platform" when setting number of global threads to be used

### ISSUE THREAD

**Issue by mtb0x1** [rayon-rs/rayon#1081]
(rayon_wasm v1.6.2).

Running the code below in browser after compiling it to wasm, results in an error. 

```rust
use rayon_wasm::ThreadPoolBuilder;


let cpus_in_use =5;
ThreadPoolBuilder::new()
.num_threads(cpus_in_use)
.build_global()
.unwrap();
```

Error :
```log
value: ThreadPoolBuildError { kind: IOError(Error { kind: Unsupported, message: "operation not supported on this platform"})}
```

is this an expected behavior ? if yes what are the alternatives if there are any ?

Thanks.

**Comment by cuviper** [comment]
`rayon-wasm` is an unofficial forked publication, as noted here: <https://github.com/rayon-rs/rayon/pull/1019#issuecomment-1616981253>. Please use rayon 1.7.0.

That wasm support is just a fallback that lets rayon work single-threaded, but that's only applied when you leave `num_threads` unspecified. The target does not support threads, so `std::thread::spawn` is returning `Unsupported`.

With Rust nightly, you can build a version of the target with atomics, and threading may work. See the documentation here: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon

There are also proposals in motion to add real supported WASI threading: <https://github.com/rust-lang/compiler-team/issues/574>, <https://github.com/rust-lang/compiler-team/issues/607>, <https://github.com/rust-lang/compiler-team/issues/661>.
