### ISSUE TITLE
Way to have assertion whether something is outside of a rayon task

### ISSUE THREAD

**Issue by solomatov** [rayon-rs/rayon#1100]
I have some code which blocks (i.e. waits for a mpsc queue). Such code is bad for running inside of rayon. Is there any way to check whether the current code is inside of rayon task or not? I want to create assertions to make sure that this code isn't called from such an inappropriate context and prevent deadlocks.

**Comment by cuviper** [comment]
You can check [`rayon::current_thread_index()`](https://docs.rs/rayon/latest/rayon/fn.current_thread_index.html), which will return `None` outside of any pool.

**Comment by solomatov** [comment]
@cuviper Thank you. That's exactly I was looking for!
