### ISSUE TITLE
Tag missing for release 1.10.0

### ISSUE THREAD

**Issue by paolobarbolini** [rayon-rs/rayon#1149]
Hi! While scraping our dependencies we've discovered `rayon` v1.10.0 to be missing the git tag on this repo. Could you add it? The exact git commit from the release can be found from https://docs.rs/crate/rayon/1.10.0/source/.cargo_vcs_info.json

**Comment by cuviper** [comment]
Sorry about that! I already had the tag locally, but I forgot to push it. Done!
