### ISSUE TITLE
Documentation for `ParallelIterator::fold` and/or `ParallelIterator::reduce` seam to be incorrect

### ISSUE THREAD

**Issue by BlockListed** [rayon-rs/rayon#1153]
The documentation for [`ParallelIterator::fold`](https://docs.rs/rayon/1.10.0/rayon/iter/trait.ParallelIterator.html#method.fold) currently (1.10.0) shows the following examples:
```rust
use rayon::prelude::*;

let s =
    ['a', 'b', 'c', 'd', 'e']
    .par_iter()
    .map(|c: &char| format!("{}", c))
    .reduce(|| String::new(),
            |mut a: String, b: String| { a.push_str(&b); a });

assert_eq!(s, "abcde");
```

```rust
use rayon::prelude::*;

let s =
    ['a', 'b', 'c', 'd', 'e']
    .par_iter()
    .fold(|| String::new(),
            |mut s: String, c: &char| { s.push(*c); s })
    .reduce(|| String::new(),
            |mut a: String, b: String| { a.push_str(&b); a });

assert_eq!(s, "abcde");
```
If the docs for [`ParallelIterator::reduce`](https://docs.rs/rayon/1.10.0/rayon/iter/trait.ParallelIterator.html#method.reduce) are to be believed, then the operation passed to it has to be associative, which `String::push_str` definitely isn't. Therefore according to my understanding of rayon, at least one of these two is incorrectly documented.

**Comment by adamreichold** [comment]
> the operation passed to it has to be associative, which String::push_str definitely isn't

Isn't it? If you ignore the identity of the underlying storage, then `a.push_str(&b)` is just `a` concatenated with `b`. It only reuses `a`'s memory to avoid an unnecessary allocation.

In particular, if `a`, `b` and `c` are `String`, then

```rust
a.push_str(&b);
a.push_str(&c);
```

stores the same value in `a` as

```
b.push_str(&c);
a.push_str(&b);
```

**Comment by adamreichold** [comment]
Or put differently, the operation is

```rust
fn concat(mut a: String, b: String) -> String {
  a.push_str(&b);
  a
}
```

which does fulfil

```rust
concat(a, concat(b, c)) == concat(concat(a, b), c)
```

**Comment by BlockListed** [comment]
Just realized my issue, I confused associative with commutative. My understanding was that if I had a list `[a, b]`, turned it into a parallel iterator and called reduce on it, it was not determined if the reduction function `f(x,y)` was called as `f(a, b)` or `f(b, a)`.

**Comment by BlockListed** [comment]
Probably should've clicked on the link in the `reduce` docs, however the fact that the example for `reduce` was commutative didn't help my confusion.

**Comment by cuviper** [comment]
We do preserve the order of operands, with the exception of `par_bridge()`.
