### ISSUE TITLE
Slowdown when using deeply nested vector

### ISSUE THREAD

**Issue by arnabanimesh** [rayon-rs/rayon#1154]
OS: `Windows 11 23H2 22631.3296 (64 bit)`
Rust version: `1.77.1`
Rayon version: `1.10.0`

Minimum reproducible example elaborating the issue:
```rust
use rayon::prelude::*;

#[allow(dead_code)]
#[derive(Clone)]
struct DummyStruct {
    x: i32,
}

fn f() -> Vec<DummyStruct> {
    vec![]
}

fn parentf() -> Vec<DummyStruct> {
    // Works properly on a simple vector
    // let _: Vec<Vec<Vec<Vec<Vec<DummyStruct>>>>> = Vec::new();
    // Slows down considerably on a level 4 nested vec with a struct
    let _: Vec<Vec<Vec<Vec<Vec<DummyStruct>>>>> =
        vec![vec![vec![vec![Vec::new(); 1000]; 1000]; 2]; 2];
    f()
}

fn solve(idx: usize) {
    parentf();
    // To check where it is slowing down
    println!("{}",idx);
}

fn main() {
    (0..800).collect::<Vec<usize>>()
        .par_iter()
        .for_each(|&idx| solve(idx));
}
```

**Comment by arnabanimesh** [comment]
Similar bug reported to `tokio` too: https://github.com/tokio-rs/tokio/issues/6458

**Comment by cuviper** [comment]
Note that rayon is not involved in that deeply-nested `Vec`, apart from getting you into that multi-threaded context in the first place. You should use a profiler, but I expect you'll see that most of your time is either in alloc/dealloc or the `Drop for Vec` itself (at multiple levels).

**Comment by arnabanimesh** [comment]
@cuviper I also think that alloc and dealloc might be the issue, but I didn't think that creating nested vectors would have this much overhead when run parallelly. I will check using profiler though.

Check the code now, I have simplified it further. It turns out recursion was not the problem.

**Comment by arnabanimesh** [comment]
On WSL2 Ubuntu 22.04 it runs fine, but I can't generate `flamegraph` (Used `cargo-flamegraph` and `inferno`) from `perf.data` there due to IO/CPU overload and out of order events. I think there is some issue with how Windows allocates data or the Rust binary generated on Windows.

**Comment by arnabanimesh** [comment]
Posted the issue in rust repo: https://github.com/rust-lang/rust/issues/123447

**Comment by arnabanimesh** [comment]
Turns out heapalloc was the culprit as mentioned in the issue I posted in Rust Lang repo.
