### ISSUE TITLE
Question about return types from .map()

### ISSUE THREAD

**Issue by kurt-rhee** [rayon-rs/rayon#1176]
Hello, 

I have two functions.  Each of the two functions returns a tuple of enum variants as its return value.  For function one the return type over the map is `(Vec<T>, Vec<U>)`, but for function two the return type is `Vec<(T, U, V)> `.  Am I mapping over these functions incorrectly?

Function 1:
```
pub fn nrel_2008(
    time_step: &chrono::DateTime<FixedOffset>,
    latitude: &Latitude,
    longitude: &Longitude,
    elevation: &Elevation,
    pressure: &Pressure,
    temperature: &TemperatureAmbient,
) -> (SunAzimuth, SunZenith) 
```
```
let inputs = (time_series, &weather_station.temperature_ambient).into_par_iter();
let (azimuth_series, zenith_series) = inputs
            .map(|(time_step, t_amb)| {
                nrel_2008(time_step, latitude, longitude, elevation, &pressure, t_amb)
            })
            .collect()
```

Function 2:
```
    fn convert_spherical_to_cartesian(
        azimuth: f64,
        zenith: f64,
    ) -> (SunCartesianX, SunCartesianY, SunCartesianZ)
```

```
    let spherical_coordinates = (solar_azimuth_series, solar_zenith_series).into_par_iter();
    let spherical_coordinates: Vec<(SunCartesianX, SunCartesianY, SunCartesianZ)> =
        spherical_coordinates
            .map(|(azimuth, zenith)| convert_spherical_to_cartesian(azimuth, zenith))
            .collect();
```

**Comment by cuviper** [comment]
I don't understand the question. Are you getting errors from this? Are the return types not what you intended?

**Comment by kurt-rhee** [comment]
Hello, 

Apologies for my unclear question.  I am not getting errors, but you are right that my return types are not what I expected.

The first function returns a tuple of vectors, while the second function returns a vector of tuples.  I am not sure why function 1 would return a different type than function 2 given the underlying functions that are being mapped.

**Comment by cuviper** [comment]
The [`collect()`](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.collect) method is generic, where its return type can be anything that implements [`FromParallelIterator`](https://docs.rs/rayon/latest/rayon/iter/trait.FromParallelIterator.html), and that is usually inferred from the surrounding context. So in the first case:

```rust
let (azimuth_series, zenith_series) = (/*iter*/).collect();
```

Your `let` pattern is forcing the result to be a tuple, and you must have some other code that is driving type inference for each of those "series" to end up fully resolved as `(Vec<T>, Vec<U>)`. Rayon has an implementation of `FromParallelIterator` for tuple pairs that acts pretty much like [`unzip()`](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.unzip).

In the second case, your code is explicitly forcing the `Vec<(X, Y, Z)>` type for `collect()`:

```rust
let spherical_coordinates: Vec<(SunCartesianX, SunCartesianY, SunCartesianZ)> = (/*iter*/).collect();
```

We don't have a direct way to collect `(Vec<X>, Vec<Y>, Vec<Z>)`, if that's what you wanted, but you *can* use nested tuple pairs for this if you produce parallel items of the same shape, like:

```rust
let (vx, (vy, vz)) = (/* iter with Item=(x, (y, z)) */).collect();
// or
let ((vx, vy), vz) = (/* iter with Item=((x, y), z) */).collect();
```

**Comment by kurt-rhee** [comment]
Thank you!  That was a very clear explanation.  Closing as complete.
