### ISSUE TITLE
`set working-directory` should create that dir if missing

### ISSUE THREAD

**Issue by nyurik** [rayon-rs/rayon#1187]
Consider a "wrapping" scenario: some big git repo does not want to introduce `justfile`, but some developers really want to have it.  So they create a small repo that only contains `justfile`, and in there they set the working dir and init it (real life [example](https://github.com/nyurik/just-maplibre-native))

```just
# does not work -- repodir does not yet exist
set working-directory := 'repodir'

init:
  # does not work because by now, repodir would somehow exist, and git clone would fail
  git clone ...
```

The issue with the above is that if `repodir` does not yet exist, it will fail because `shell` won't be able to start in a missing directory.  If `repodir` does exist, `git clone` should be skipped.

The first problem could have been fixed if the `set` command was a regular sequence operation, and because it requires a string:

```just
# does not work because `set` is executed first
_ := `mkdir -p repodir`
set working-directory := 'repodir'

# does not work because `set` takes a literal string
set working-directory := `mkdir -p repodir && echo "repodir"`

# in theory this COULD work if we have a `mkdir` function?  Possibly `mkdir` could even return that same string?
set working-directory := mkdir('repodir') and 'repodir'
```

The `git clone` could be solved with some check to see if the dir is empty, and then run a `rm repodir && git clone ...`

**Comment by cuviper** [comment]
Wrong repo? I'm guessing you want https://github.com/casey/just

**Comment by nyurik** [comment]
LOL, oops, my appologies :)  Too many tabs open at once!
