### ISSUE TITLE
Unhelpful default panic message in `spawn*()` functions

### ISSUE THREAD

**Issue by teor2345** [rayon-rs/rayon#1208]
When rayon encounters a panic in a job launched by `spawn*()`, and there's no panic handler defined, it logs a minimal error message: ["Rayon: detected unexpected panic; aborting".](https://github.com/rayon-rs/rayon/blob/6ca44bd18e7e6004d0ad3e17137da030ca1adf2a/rayon-core/src/unwind.rs#L28)

This message doesn't contain the `PanicHookInfo`, which makes panics harder to diagnose.

We use rayon extensively, as do multiple libraries we depend on. So it's tricky for us to set a panic handler on every rayon thread pool.

Is it possible to change [`Registry::catch_unwind()`](https://github.com/rayon-rs/rayon/blob/6ca44bd18e7e6004d0ad3e17137da030ca1adf2a/rayon-core/src/registry.rs#L365) so it prints the `PanicHookInfo` when there's no panic handler?

We're happy with the "abort if there's no panic handler set" behaviour, and don't want that changed. It would be a surprising change for some projects.

**Comment by cuviper** [comment]
> When rayon encounters a panic in a job launched by `spawn*()`, and there's no panic handler defined, it logs a minimal error message: "Rayon: detected unexpected panic; aborting".

Yes, but doesn't std's global panic hook print something first?

> This message doesn't contain the `PanicHookInfo`, which makes panics harder to diagnose.

Rayon never has that info at all, because [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) just returns `thread::Result`, where the error is an opaque `Box<dyn Any>`. I think that's the same object that `PanicHookInfo::payload` would return as a reference.

We could potentially try string downcasting to print, but I'm not sure that we _should_ if the global panic hook is already printing that along with detailed location info.

**Comment by teor2345** [comment]
> > When rayon encounters a panic in a job launched by `spawn*()`, and there's no panic handler defined, it logs a minimal error message: "Rayon: detected unexpected panic; aborting".
> 
> Yes, but doesn't std's global panic hook print something first?

Yeah, that's super weird. We have a bug report with normal logging to stdout, and rayon's message to stderr, but no panic message from the default hook. (Which, as you say, is printed to stderr *before* `catch_unwind()` is called.)

It's unlikely that it got caught in a buffer before exit, because the default hook writes a line with the thread name, in a similar way to rayon.

> > This message doesn't contain the `PanicHookInfo`, which makes panics harder to diagnose.
> 
> Rayon never has that info at all, because [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) just returns `thread::Result`, where the error is an opaque `Box<dyn Any>`. I think that's the same object that `PanicHookInfo::payload` would return as a reference.
> 
> We could potentially try string downcasting to print, but I'm not sure that we _should_ if the global panic hook is already printing that along with detailed location info.

Understandable, and sorry for the noise. I guess we'll wait and see if it happens again, and hope to get the panic hook message this time!
