### ISSUE TITLE
support `collect()` (and `collect_into()`) for Vec with bounded iterator types

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#146]
We can extend the current `collect_into()` support for vectors beyond *exact* iterators into *bounded* iterators without much difficulty.

Currently, the [collect consumer](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/consumer.rs) [knows how many items it expects to be written after each split](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/consumer.rs#L14). As items are pushed, it [asserts that it doesn't receive too many](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/consumer.rs#L80). At the end, it [asserts that it did not get too few](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/consumer.rs#L96). (Note that we cannot trust the producer, which is safe code.) The result of collection is [just the `()` type](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/consumer.rs#L45).

An O(n^2) approach to fix this, which is probably not good, is that the collect consumer would return the number of items written up to our caller as the result of collect (currently, the result is `()`). In the reduction step, if the number of items produced on the left-side is less than the expected number, we would do a `memcpy` to shift the items from the right-side over to their expected location. Then, [when we call `set_len`](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/collect/mod.rs#L35) at the end, we would naturally recover just the actual data that was written.

An O(n) approach would be that we do not move the items as we reduce, but rather we keep a vector of those points where gaps occurred. We could do this by returning a `LinkedList<(usize, usize)>`, where each folder returns the pair of the starting index and the number of items that it wrote. The easiest thing to do (and quite likely the fastest in practice) is to sequentially compact by iterating over those pairs and shifting them into place.

~~We could also parallelize the final step by sequentially computing where each segment should be stored to (you have to sum up the preceding statements to do it, so sequential is certainly better, since this list is short) and then doing another parallel walk, where for each pointer at index `j` we consult this list (which is now shared and immutable) to figure out where to write `j` to. I doubt this will be a win except perhaps for very large vectors.~~

cc @jwilm

**Comment by nikomatsakis** [comment]
PS -- if anybody can think of a better way to do this, I'm all ears. Also, it'd be nice if we could add a method to `BoundedParallelIterator` that lets you dynamically *test* if the range is exact or not, so that we can skip building the linked list if this is (in fact) an `ExactParallelIterator` (obviously we'd still have to *test* that the write number of things were written).

**Comment by cuviper** [comment]
> We could also parallelize the final step by sequentially computing where each segment should be stored to (you have to sum up the preceding statements to do it, so sequential is certainly better, since this list is short) and then doing another parallel walk, where for each pointer at index j we consult this list (which is now shared and immutable) to figure out where to write j to. I doubt this will be a win except perhaps for very large vectors.

This isn't safe if we're shifting in-place, as you have to be sure the previous occupants have already vacated.  But I suspect this will be memory bound anyway, just a series of `memmove`, so I doubt it would help much to do it in parallel -- might even *hurt* due to cache performance.

**Comment by nikomatsakis** [comment]
> This isn't safe if we're shifting in-place

Ah, yeah, that's true. Anyway I agree likely not worth it.

**Comment by nikomatsakis** [comment]
> This isn't safe if we're shifting in-place

Ah, looking back at some old code I had that did something like this, I think it created a new vector that was just the right size and compressed from the source into the new vector (in which case you don't have this concern).

**Comment by cuviper** [comment]
We don't have `BoundedParallelIterator` anymore.
