### ISSUE TITLE
Will the threadpool be shared if rayon is used in two crates included in the same project?

### ISSUE THREAD

**Issue by pedrocr** [rayon-rs/rayon#174]
I've just used rayon to replace my hand-rolled parallelization in rawloader:

https://github.com/pedrocr/rawloader/commit/a33ad0e40c1a5c5cdec573484f7dcba466772ee6

The performance is pretty much the same even though now I'm doing the parallelization per line instead of splitting the work in the number of threads equal to the number of CPUs. So the rayon overhead is indeed low.

This left me with a question though. Since rawloader is a library, if someone builds a project that includes rawloader and another crate that uses rayon will both share a threadpool or each get their own and thus have two threadpools in the same program? It would be great if both used the same so that you don't end up generating a lot more running threads than you have CPUs but I wanted to confirm that was the case.

**Comment by cuviper** [comment]
The thread pool is managed in a static global, so yes it should be shared, as long as you only have one version of rayon in your project.

But if your project has dependencies with conflicting versions of rayon, then cargo will build multiple versions independently, and those can't share threads.  I think it will still be just as safe, but oversubscribed on threads.

**Comment by cuviper** [comment]
Actually, I don't think that is safe if you have any callback loops.  If all threads of rayon A make calls into a library using rayon B, and that transitively makes calls that would inject jobs back to A, then this may never complete.  Those A->B calls will block on B's job latch, rather than stealing other A work in the meantime.  Then the B->A calls will similarly block on A's job latch, with no A threads left to do the work.

If there's a way to make a compilation error with multiple rayons, we should seriously consider that.

**Comment by pedrocr** [comment]
Sounds great then. I was thinking about this some more and there's actually a downside to this which is potential added latency. Say you only have a single CPU (to simplify) and have done join(|| a(), || b()) where a() takes 5 min, and then do join(|| c(), || d()) from another thread where each of those is a 1s calculation. You'll only start doing c() and d() once a() ends and thus latency has been greatly affected.

**Comment by nikomatsakis** [comment]
@cuviper can you spell out the scenario you are concerned about in a bit more detail? It seems plausible, but I can't quite come up with a convincing example. At minimum, it seems pretty unlikely to occur in practice. 

That said, having thought about this some, I think the best "fix" for this is breaking the thread-pool out into its own crate. I would expect that to iterate relatively slowly relative to the rest of Rayon, and probably it wouldn't make breaking changes very often. I was thinking of doing that after we finish up the work on futures and I open the PR for `spawn_async()` (which I expect to slightly affect things).

**Comment by cuviper** [comment]
Something like:

```rust
// main crate using rayon A
fn main() {
    rayon::join(foo::foo, foo::foo);
}

// crate foo using rayon B
fn foo() {
    rayon::join(bar::bar, bar::bar);
}

// crate bar using rayon A
fn bar() {
    rayon::join(|| (), || ());
}
```

Every `join` is called outside its crate's threadpool, so will inject jobs and block on their completion.
- `main` injects `foo` into threadpool A
- `foo` injects `bar` into threadpool B
- `bar` injects its closure into threadpool A
  - if that threadpool has <=2 threads, then it's fully blocked in `foo`, and we're stuck.

In fact, I think you could hit this with a single rayon too, if you have a `ThreadPool::install` cycle through separate pools.  Or even more generally, if your rayon jobs block on an external condition which itself tries to use rayon to complete, we could become thread-starved.  e.g. if `foo` above knew nothing about rayon, just did a plain `thread::spawn` to call `bar`.

Blocking is already a rayon anti-pattern, of course, but this might be a surprising path to it.  I don't know how likely it might occur in practice.

**Comment by cuviper** [comment]
Here's a self-contained working example:

```rust
extern crate rayon;

use std::thread;

fn main() {
    let config = rayon::Configuration::new().set_num_threads(1);
    rayon::initialize(config).unwrap();
    rayon::join(foo, || ());
}

fn foo() {
    thread::spawn(bar).join().unwrap();
}

fn bar() {
    rayon::join(|| (), || ());
}
```

When you imagine these things might be in different crates, then their isolated behavior may be totally reasonable, but in combination they can lock the threadpool.

**Comment by nikomatsakis** [comment]
@cuviper ah, right, ok, thanks! :)

**Comment by cuviper** [comment]
I've been trying to think of ways to mitigate this.  If we get dynamic threads in the pool, then one possibility is that the calling thread should always join the pool if it's not already a member, so we know there's at least one unblocked worker, the caller itself.  (If the caller is already a member of a different pool, it would have to temporarily leave that.)  Maybe some heuristic can scale this back so we don't oversubscribe threads, like leaving it alone if there are already idle workers ready.

**Comment by nikomatsakis** [comment]
@cuviper that sounds quite complex. If we did allow for pools to grow/shrink, then I wouldn't have the threads migrate, it might well be simpler to just have the pool grow a new thread when it seems like no progress is being made. The idea would be to cope also with people doing blocking I/O and that sort of thing. I believe the Java FJP does this, and I recall reading it about in [the excellent SEDA thesis](https://cs.uwaterloo.ca/~brecht/servers/readings-new/mdw-phdthesis.pdf) as well.

**Comment by cuviper** [comment]
Detecting "progress" sounds tricky to me too, but that's nice if there's prior art to consult.

**Comment by nikomatsakis** [comment]
@cuviper I think the idea would be that there are pending work items in queues but no threads stealing them.

**Comment by cuviper** [comment]
But how do you know whether there's no stealing because they're stuck, or just busy on their own?

**Comment by nikomatsakis** [comment]
@cuviper Not sure =) I'm confident there are some heuristics involved. It may be that you don't care too much about the difference, anyway.

**Comment by cuviper** [comment]
We've since release rayon-core 1.0 to hopefully ensure a common pool implementation (at least in the rayon ecosystem), and #449 even solved the problem of `ThreadPool::install` cycles between pools!
