### ISSUE TITLE
cleanup public surface of parallel iterator API

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#228]
The parallel iterator public API contains a whole bunch of random modules and things (e.g., for each operation, like `reduce`). We should clean it up to be more minimal, only exporting the stuff we really need, and putting all the associated types in a flat space (probably still keeping the `par_iter` module though).

### Current status

Much progress has been made in #247.

This established some principles:

- the `par_iter` module is now called `iter`; it contains only things specific to the traits themselves
- parallel iterator types for existing collections and types (e.g., for slices) are named `FooIter` (e.g., `SliceIter`) and placed in top-level modules (e.g., `rayon::slice::SliceIter`)
- we generally are not exposing the means to "re-implement" the combinators like `map` unless we have a reason to do so (e.g., there is no public constructor on `iter::map::Map`, nor free function version of the `map()` method). This is because those methods are not expected to be overridden (and, if they are, it's unlikely that `Map` would be of use). We can revisit this if there is demand.

### Open questions to be resolved

- [x] What should we call `iter::internal` and should it move somewhere else in the hierarchy?
- [x] What should we do about the `MapOp` hierarchy in `iter`?
- [x] What should we do about the `ReduceOp` hierarchy in `iter`?
- [x] Should we make the `ChunksIter` stuff less general, more like `ParallelString`?
    - right now, its a trait that acts as though many types might implement it, though only `[]` does so, and it's not clear it's general enough for other things yet

**Comment by Kerollmops** [comment]
I think that rewriting [Type Parameters to be more concise](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html) can be a good thing, no ?

**Comment by nikomatsakis** [comment]
@Kerollmops I ... obviously strayed from the style guidelines intentionally, but I think I've decided that the longer names are not so readable. CamelCase I am actively against, though, because I tried it and found it kind of confusing (it was hard to tell which is a type parameter and which is a type).

**Comment by nikomatsakis** [comment]
That said, it's not part of the public API.

**Comment by nikomatsakis** [comment]
(In the sense that it's not a breaking change if we change them later.)

**Comment by nikomatsakis** [comment]
@Kerollmops see https://github.com/nikomatsakis/rayon/issues/249

**Comment by nikomatsakis** [comment]
@cuviper I moved the comments of yours that I did not address in #247 into a list of "unresolved questions" at the top of this issue.

**Comment by cuviper** [comment]
I've got several PRs to rename iterators with symmetry to their sequential counterparts in libstd:
#272 #274 #275 #276

`OptionIter` is a little weird, as that one iterator implements the 6 variations of `Option`/`Result` by value/`&`/`&mut`.  If we're mirroring libstd, these should each get their own type, but that's an annoying amount of boilerplate.  Macros might help, but the constraints of each are slightly different enough to make that challenging too.  Maybe we should just bite that bullet as a one time cost, as much as I prefer DRY.

Similarly, in `iter::collections` we have various `IntoParallelIterator` which are exposing their underlying implementations, mostly vectorized into `vec::IntoIter`, and a couple others.  It seems better for the API surface if these also get independent iterator types, wrapping whatever they need underneath, and these could also mirror the layout of `std::collections`.  But again, lots of boilerplate.

**Comment by nikomatsakis** [comment]
@cuviper could we handle `OptionIter` with a type alias?

**Comment by nikomatsakis** [comment]
(Not sure if we *should* mind you)

**Comment by cuviper** [comment]
A type alias is still seen as an identical type, by design, so it doesn't really help IMO.  We'd have multiple aliases to the same thing, which still locks us into that one thing as far as semver goes.

But I have something decent working with macros creating newtype wrappers, hiding all the boilerplate.  I'll try to clean that up for a PR soon.

**Comment by nikomatsakis** [comment]
> We'd have multiple aliases to the same thing, which still locks us into that one thing as far as semver goes.

Yes, I was assuming we were ok with that, but just would like the names to be "guessable".

**Comment by cuviper** [comment]
I'd be somewhat ok with `OptionIter`, but less so with all the collections exposing their implementation.  In solving the latter with newtypes, the former is easy too.

**Comment by cuviper** [comment]
I marked the `ReduceOp` and `ChunksIter` question completed.  I started to address `MapOp` in #284.  Not sure what, if anything, to do about `iter::internal` -- it seems OK as long as we document its purpose.

**Comment by nikomatsakis** [comment]
Yeah, I'm ok with `internal`. At most I'd just bikeshed its name, but I can't think of a better one. I feel like it's "for implementors", but `impl` is a keyword and `implementor` is too long. =)

**Comment by cuviper** [comment]
- `MapOp` has been gone since #304.
- `iter::internal` became `iter::plumbing` in #463.

I think we're *probably* happy with the API at this point, except perhaps addressing #417.

**Comment by nikomatsakis** [comment]
Looks like this is all done.
