### ISSUE TITLE
[docs] rayon-core module

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#231]
Task: write `//! foo` docs in `rayon-core/src/lib.rs` documenting the `rayon-core` module itself. Rayon-core represents the "core, stable" APIs of Rayon: `join`, `scope`, and so forth, as well as the ability to create custom thread-pools with `ThreadPool`. 

Maybe worth mentioning: users are not necessarily intended to directly access rayon-core; all its APIs are mirror in the rayon crate. To that end, the examples in the docs use `rayon::join` and so forth rather than `rayon_core::join`.

`rayon-core` aims to never, or almost never, have a breaking change to its API, because each revision of rayon-core also houses the global thread-pool (and hence if you have two simultaneous versions of rayon-core, you have two thread-pools).

**Comment by cuviper** [comment]
> rayon-core aims to never, or almost never, have a breaking change to its API, because each revision of rayon-core also houses the global thread-pool (and hence if you have two simultaneous versions of rayon-core, you have two thread-pools).

Aside on this point - we should then make sure that the initial `rayon-core` we publish has the semantic version we want to stick with for a while.  It's 0.1 right now.

**Comment by nikomatsakis** [comment]
@cuviper Yes, I was wondering about that. I was thinking we should just start at 1.0.

**Comment by nikomatsakis** [comment]
Taking off the milestone.

**Comment by iRaiko** [comment]
Hey, I'm a newer developer to rust and I was wondering if I could help with this?

**Comment by cuviper** [comment]
@iRaiko sure, documentation is a great place to contribute, especially from someone with less familiarity with the code.

I don't think `rayon-core` really needs to say too much itself, because we mostly steer users toward the same interfaces re-exported in the `rayon` crate. Still, we can definitely do better than "Under construction". :construction:

**Comment by tiby312** [comment]
Should this be closed? I pulled down master, and this appears to already be done.

**Comment by cuviper** [comment]
Ah, yes, that would be from #809.
