### ISSUE TITLE
[docs] document the `Scope` struct

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#233]
The `scope::Scope` struct in `rayon-core` needs documentation. The use of scopes is reasonably well documented on the `scope::scope` function, so probably the type itself just needs to say something like "Represents a fork-join scope which can be used to spawn any number of tasks. See `scope()` for more information."

**Comment by dethoter** [comment]
Can this issue be closed?

**Comment by cuviper** [comment]
Ah, yes, thanks!
