### ISSUE TITLE
[docs] the `ThreadPool` struct in `rayon-core` needs documentation

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#235]
The `ThreadPool` struct represents a user created thread-pool (as opposed to the default, global threadpool). It needs `/// foo` docs.

Some things to say:

- Create a new thread-pool with `ThreadPool::new` (!). You can use the configuration to specify the number or names of its threads, how to handle uncaptured panics, and so forth.
- There are two ways to use the thread-pool:
    - The first is that you can execute `ThreadPool::install()`. This will execute a closure in one of the threadpool's threads. Any other Rayon operations -- like parallel iterators, `join()`, or `scope()` -- will then execute in the context of this thread-pool.
    - The second is that you invoke `ThreadPool::spawn_async()` or `ThreadPool::spawn_future_async()`. These methods will inject jobs into the thread-pool that are not tied to your current stack frame; however, those jobs cannot access data owned by the stack.
- When the thread-pool is dropped, that is a signal for its threads to terminate. Once they have completed executing any remaining work that you have spawned, they will automatically terminate.

**Comment by bobbo** [comment]
Can this be closed given #325 was merged?

**Comment by cuviper** [comment]
Sounds good, thanks!

**Comment by Enamex** [comment]
Are there any non-doc [help wanted] issues remaining or coming?

**Comment by cuviper** [comment]
@Enamex I would say docs are where we're most lacking, but I'll try to remember to file any other ideas as I have them.  I just filed #465, and maybe you could check if someone is still working on #330.

There are also open questions, like how to create parallel iterators from arbitrary iterators (#46) or vice versa (#210).  I guess those could be considered [help wanted] in the sense of "help, we don't even know how to do this!"  We tend to only tag [help wanted] on mentor-able issues, but anyone is welcome to chime in on other issues too.
