### ISSUE TITLE
[docs] the `rayon` crate needs documentation

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#236]
This is the main entry-point for `rayon`. It should have some nice docs, probably quite similar to the README. That is, we would want to explain what rayon is all about, give some quick examples, and then direct people to the most important functions to learn more.

I would probably include direct links to:

- The `ParallelIterator` trait
- The `join()` and `scope()` methods (located in rayon-core)
- The `spawn_async()` and `spawn_future_async()` methods (located in rayon-core)
- The `ThreadPool` type for creating custom thread-pools (located in rayon-core)

**Comment by KodrAus** [comment]
I like the idea of introducing a reader to the breadth of the `rayon` ecosystem using a top-down, task-based approach, like @nikomatsakis has pretty much described in the set of bullet points.

I'm not sure if it's already been discussed before, but another idea might be to keep the docs focused on API discovery and work on a separate book for exploring `rayon` in a more structured way, like `https://serde.rs`. Although it's probably easier to fill out all that information in the crate docs first, and then pull it out into a book at another point.

Is the idea of this issue that we flesh out the _Parallel Iterators_ and _Divide and conquer with `join`_ sections in the crate root and add some new ones for `futures` and the `ThreadPool`?

**Comment by cuviper** [comment]
FWIW, the futures stuff is now in its own `rayon-futures` crate, and given that it's still unstable, I wouldn't bother mentioning it in `rayon` or `rayon-core` docs at all yet.

A book sounds great, but I'd prioritize improving the crate docs first. :)

**Comment by nikomatsakis** [comment]
We have such documentation but we still want to revisit it. This is the initial landing place, after all.

**Comment by nikomatsakis** [comment]
@KodrAus is going to do a survey.

**Comment by KodrAus** [comment]
I'm making a start on this now in a branch including #511 and #512.

**Comment by KodrAus** [comment]
Ok I've done a first pass over the docs and made some notes in [a Dropbox Paper](https://paper.dropbox.com/doc/rayon-docs-HoJk4CftX7Fl8LfnVoMBb). It's organised by module/type with some general thoughts on the docs in each. Some of it I think is probably already covered by issues here. I figured we could go over that and try clarify any other points into a concrete list.

**Comment by cuviper** [comment]
Let's call this done, for the milestone's sake. 😄 
(Future work can be filed in more specific issues.)
