### ISSUE TITLE
[docs] the `ReduceOp` trait and its impls need docs

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#244]
The `ReduceOp` trait has decent docs, but the methods do not. Probably they just need some comments giving a brief summary and pointing at the trait itself.

Also, the various impls such as `SUM` and `PRODUCT` have no documentation. Each of these comes from some method in `ParallelIterator` (e.g., `sum()`, `product()`), so just a brief note linking to those methods probably suffices.

**Comment by cuviper** [comment]
FWIW, these are no longer in the public API, and sum/product are now independently implemented.  Doesn't mean we can't improve internal documentation, but it's less pressing.

**Comment by cuviper** [comment]
This is no longer a thing...
