### ISSUE TITLE
Add an std::iter::repeat() equivalent

### ISSUE THREAD

**Issue by cuviper** [rayon-rs/rayon#331]
```rust
pub fn repeat<T>(elt: T) -> Repeat<T>
    where T: Clone
```

"Creates a new iterator that endlessly repeats a single element."

It should be straightforward in rayon with `T: Clone + Send`.  I think we could have both an indexed `Producer` (len `usize::MAX`) for use with `zip` etc. and an infinite `UnindexedProducer`, depending on whether it goes through `drive`/`with_producer` or `drive_unindexed`.

The novelty `std::iter::once()` and `std::iter::empty()` could also be implemented, probably just wrapping `Option::Some` and `None`.

**Comment by ChristopherDavenport** [comment]
I'll take a run at this one.

**Comment by Enamex** [comment]
Doesn't #397 close this?

**Comment by cuviper** [comment]
Yep, thanks!
