### ISSUE TITLE
replace the thread-id hack with `thread-id` crate

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#335]
Turns out there is a crate for getting the id of the current thread:

https://crates.io/crates/thread-id

We currently use a kind of [nasty hack instead](https://github.com/nikomatsakis/rayon/blob/master/src/iter/internal.rs#L146-L152), where we take the address of a thread-local variable. We should replace that with `thread-id`. 

I'm marking this as Help Wanted since it seems like a good starter issue.

**Comment by cuviper** [comment]
Well... *maybe*.  As that hack notes, it really doesn't care about the actual value, just that it's unique per thread.  I fear that a call to get an OS thread identifier might hurt performance.  I guess that depends on how fast TLS is in comparision, but I also hope that Rust will someday use static TLS, which makes that something like just a register and offset.

Alternatively, our own `ThreadPool::current_thread_index()` might also suffice, although we'd also need a way to get the current thread pool, and use a default like `usize::MAX` if outside any pool.

**Comment by nikomatsakis** [comment]
> Well... maybe. As that hack notes, it really doesn't care about the actual value, just that it's unique per thread. I fear that a call to get an OS thread identifier might hurt performance. I guess that depends on how fast TLS is in comparision, but I also hope that Rust will someday use static TLS, which makes that something like just a register and offset.

Rust already does use static TLS, at least on linux. I also believe that this is how `pthread_self()` works, but I agree it's worth benchmarking.

**Comment by cuviper** [comment]
When I say static TLS, I'm referring to `-ftls-model=initial-exec`.  You can see this in `readelf -d` that the flags will include `STATIC_TLS`.  I've never seen this on a Rust executable, but even with GCC it's only the default for non-PIC compilation.  (The space for static TLS could get exhausted by dynamic library loads.)  Dynamic TLS is still native ELF, but IIRC it requires libc calls to get the thread area every time.

In glibc, `pthread_self()` returns the arch-specific `THREAD_SELF`, which [on x86_64](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/nptl/tls.h;h=9b8ad82550f9ed719a5a18cf16c5b9fc346cdd28;hb=HEAD#l172) is just an `fs` offset, much like static TLS.  Compared to dynamic TLS which must call glibc's `__tls_get_addr()`... hmm, ok `pthread_self()` might be better for us after all.

Anyway, what I vaguely recall now is that the splitter TLS stuff barely registered at all on perf profiles, even in our various microbenchmarks, so we _probably_ don't need to worry too much.

**Comment by cuviper** [comment]
Oh, the other dissatisfying part of `thread_local!` is that it's so dynamic with lazy init.  If we could use a direct `#[thread_local]` in this `thief_id()`, then I'd expect it to get much tighter code.

I guess that's another point in favor of `thread-id`.  So yeah, if someone wants to try this, please don't be turned off by my hesitation -- let's make an actual comparison!

**Comment by nikomatsakis** [comment]
@cuviper ok you've exceeded my knowledge of TLS internals. That said, I *think* that `thread_local!` will use `#[thread_local]` under the hood. But I'm not really sure. @alexcrichton would know more.

**Comment by alexcrichton** [comment]
Ah looks like @cuviper knows all about the impl of `thread_local!`, I believe everything he's mentioned is correct. The [asm confirms](https://gist.github.com/015f6968f8cbd486688dc2964b8a9136) that calls go through `__tls_get_addr` on Linux.

That being said yeah I've never seen this in a profile. I'd love to have a mode of `thread_local!` that accepts a constant initializer though to avoid the lazy init!

**Comment by dead10ck** [comment]
Hi guys; I'm just taking a poke around at some libz blitz tickets, and I came across this one. Forgive me if I'm asking an ignorant question, but is there a reason not to use [`std::thread::ThreadId`](https://doc.rust-lang.org/std/thread/struct.ThreadId.html)? The `thread-id` crate mentions that the only reason it exists is because something didn't exist in the stdlib before, but now there is.

In any case, it was such a simple change that I went ahead and made a branch for each: one with [`std::thread::ThreadId`](https://github.com/dead10ck/rayon/tree/threadid_std), and the other with the [`thread-id`](https://github.com/dead10ck/rayon/tree/threadid_crate) crate.

**Comment by cuviper** [comment]
Sorry, we should have mentioned it here -- I think we'll use #354 and not need a thread id at all.

Anyway, the reason not to use `std::thread::ThreadId` was that it wasn't stable at the time -- only as of Rust 1.19.  And I'm generally very reluctant to raise the minimum Rust requirement.

**Comment by dead10ck** [comment]
Oh, I see; that makes sense. Thanks for letting me know :)

**Comment by cuviper** [comment]
#354 was merged.

**Comment by mqudsi** [comment]
> Forgive me if I'm asking an ignorant question, but is there a reason not to use [std::thread::ThreadId](https://doc.rust-lang.org/std/thread/struct.ThreadId.html)?

Just an FYI for anyone reading this, `std::thread::ThreadId()` is also much slower than the alternatives proposed here and allocates with calls to `Arc`.
