### ISSUE TITLE
should `skip` preserve side-effects when running in parallel?

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#352]
In the code for `skip()`, I noticed [this call to `bridge_producer_consumer()`](https://github.com/nikomatsakis/rayon/blob/40e7efa8cd51464e9c8511ccfad21713a5d411b4/src/iter/skip.rs#L74):

```rust
let (before_skip, after_skip) = base.split_at(self.n);
bridge_producer_consumer(self.n, before_skip, NoopConsumer::new());
self.callback.callback(after_skip)
```

It seems odd to me that we do this, rather than just throw away `before_skip`. In particular, I do think that consumers can expect to be "fed" all the items that a parallel iterator promised (i.e., what it returned for `len()` or `opt_len()`). But I don't think that *producers* should necessarily expect to be "driven" by having all of their items pulled (and, in this case, discarded).

I'm inclined to drop that call to `bridge_producer_consumer()`. Thoughts?

**Comment by cuviper** [comment]
That was to maintain side-effect symmetry with `Iterator::skip` : https://github.com/nikomatsakis/rayon/pull/162#issuecomment-261684136

If you want to weaken that symmetry, then sure, we could throw the first half away, just like `take` throws away its second half.  (IOW `take` already proves that producers may be incompletely driven.)

**Comment by cuviper** [comment]
For that matter, we also have many short-circuiting ops like `find_any`.  So I don't think there's any general expectation that producers will fully produce -- `skip` just needs additional consideration for side effects.

**Comment by nikomatsakis** [comment]
ah, yeah, forgot about the side-effects

**Comment by nikomatsakis** [comment]
I changed the title since I think we agree that producers are not forced to produce.

**Comment by nikomatsakis** [comment]
We decided to keep compatibility with sequential iterators. If we want a version that ignores side-effects, we can always add another method later with a different name.

**Comment by nikomatsakis** [comment]
This came up in a conversation recently -- there is some need for a method that, given an `IndexedParallelIterator`, lets you extract a subset. The person was using `skip` and `take` in conjunction to do that, but it's imperfect (particularly when it comes to side-effects). It seems like we could offer a more direct method.

**Comment by cuviper** [comment]
Maybe add something like `trim(start, end)` that we'll say explicitly doesn't run side-effects?

**Comment by nikomatsakis** [comment]
Discussed in meeting:

skip will retain its sequential-compatible semantics.

We would like to add something to allow indexed parallel iterators to be 'subsetted'. Perhaps a split operation would be ideal, since it lets you further subset both parts (and it's fully general). (You can choose what to do with the unused parts.)

**Comment by nikomatsakis** [comment]
Closing this issue but opening https://github.com/rayon-rs/rayon/issues/513
