### ISSUE TITLE
Figure out upgrade to futures `Notify` API

### ISSUE THREAD

**Issue by leodasvacas** [rayon-rs/rayon#356]
See [this thread](https://users.rust-lang.org/t/how-to-pretend-something-lives-for-static/) for previous discussion. The new `Notify` API in futures 0.1.14, which replaces the old `Unpark`, no longer takes `Arc<Unpark>` but instead takes an generic `T: Into<UnparkHandle>`, which includes `Arc<T: Notify + Sized>`.

I naively thought this meant we could get rid of the `Unpark` trait object in [make_unpark](https://github.com/nikomatsakis/rayon/blob/194945535241f3ccafd5144aa9472d50692ae664/rayon-core/src/future/mod.rs#L223-L245), but trying to make the change I was blocked because I couldn't somehow cast a `ScopeFutureContents` to live for `'static`, and @cuviper notes that using a trait object may be necessary. The new futures API doesn't support `Arc<TraitObject>` so are going to have to hack around this somehow.

**Comment by cuviper** [comment]
Where do you see `UnparkHandle` or the `T: Notify + Sized` requirement?

I think for something like [`poll_future_notify`](https://docs.rs/futures/0.1.14/futures/executor/struct.Spawn.html#method.poll_future_notify), we'll want to pass a `T` that implements `Into<NotifyHandle>` using [`NotifyHandle::new()`](https://docs.rs/futures/0.1.14/futures/executor/struct.NotifyHandle.html#method.new) with an `UnsafeNotify` pointer.  It seems like this avoids explicit `'static` lifetimes altogether, instead using plain pointer unsafety.
(But I haven't tried to implement anything yet.)

**Comment by leodasvacas** [comment]
The `T: Into<UnparkHandle>` requirement is [here](https://docs.rs/futures/0.1.14/futures/executor/struct.Spawn.html#method.poll_future_notify) and `impl From<Arc<T: Notify + 'static + Sized>> for NotifyHandle` [here](https://docs.rs/futures/0.1.14/futures/executor/struct.NotifyHandle.html). Interesting idea to roll our own `UnsafeNotify` implementation which works for an `Arc` which isn't static, seems doable.

**Comment by cuviper** [comment]
Hmm, it's not explicitly mentioned, but does `impl<T> From<Arc<T>> for NotifyHandle` imply `T: Sized`?  I always forget where it's implied one way or the other...

Anyway, `UnsafeNotify` seems cleaner than erasing lifetimes, or at least it's more direct about unsafety.

**Comment by leodasvacas** [comment]
`Sized` is implied just about everywhere. I hacked up an `UnsafeNotify` implementation, will post PR soon.
