### ISSUE TITLE
implement `intersperse` from `itertools`

### ISSUE THREAD

**Issue by nikomatsakis** [rayon-rs/rayon#385]
The `itertools` crate offers [a `intersperse` method](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.intersperse). From the docs, "An iterator adaptor to insert a particular value between each element of the adapted iterator." 

Of the existing adapters, `intersperse` somewhat resembles `repeat` (https://github.com/nikomatsakis/rayon/pull/337 -- landing soon).  It must take ownership of the element that it will be cloning; like `repeat`, we should require this value to be  `Send`. Also, like repeat, each time that we have to split the resulting iterator, we can clone the value. The main difference from `repeat` is that each time we produce an item from the base iterator, we have to next produce a clone of the intersperse value.

For more details on how parallel iterators work, see [the README](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/README.md).

**Comment by cuviper** [comment]
It almost could just use `interleave`/`interleave_shortest` (#384) with `repeat`, with that implementation detail hidden in the `drive` functions as suggested in #383.  However, `intersperse` shouldn't need to require `IndexedParallelIterator`.

**Comment by nikomatsakis** [comment]
@cuviper you know, I've been thinking for some time that `zip` doesn't actually need *both* sides to support indexed-parallel-iterator. In principle, if it is just **informed** of the split point, it can allow one side (e.g., the base) to pick the split point, and then apply it to the other side. If we did that, then you could take your approach, right?

**Comment by nikomatsakis** [comment]
(Hmm, after some discussion on gitter, I'm thinking that this technique probably doesn't work, and certainly not in the general case.)
