### ISSUE TITLE
Support a parallel iterator getting more work to do from a normal iterator

### ISSUE THREAD

**Issue by golddranks** [rayon-rs/rayon#400]
The motivation is as follows: I'm getting asynchronously produced values from a channel. For each value, there is some independent, CPU-heavy work to do. I want to maximise the resource use, and do the work in parallel if there is CPU power available and there's values available from the channel.

The types `I: Iterator<Item=T>` and/or `Receiver<T>`  don't implement the `IntoParallelIterator` trait. Is there any reason for that?

**Comment by garro95** [comment]
Similar to #46

**Comment by cuviper** [comment]
Yes, let's track it in #46.
