### ISSUE TITLE
Rename/move the iter::internal module

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#415]
This module, while an internal implementation detail, still adheres to the semver guidelines of the crate and can be useful to implementors! In the triage meeting the name "porcelain" was discussed for this as well.

**Comment by cuviper** [comment]
I do like the "porcelain" idea -- was compared to the git use of the term for low-level details that most people shouldn't need to bother with.

**Comment by cuviper** [comment]
FWIW, we had the git terminology wrong -- "porcelain" refers to the more user-friendly commands, and they call the deeper internals "plumbing".  I do like that name too -- `rayon::iter::plumbing`.
https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain
