### ISSUE TITLE
doc: Documentation examples for parallel iterator methods

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#420]
Ideally all methods on the parallel iterator traits should have an example of how they can be used!

**Comment by cuviper** [comment]
I'm reopening this per https://github.com/rayon-rs/rayon/pull/466#issuecomment-342289823

**Comment by nikomatsakis** [comment]
Assigning @cuviper to do a sweep over these methods.

**Comment by cuviper** [comment]
> Ideally all methods on the parallel iterator traits should have an example of how they can be used!

"traits" plural -- I'm inclined to include all traits in the prelude, but we're missing a lot of examples...

- [ ] `ParallelIterator`
- [ ] `FromParallelIterator`
- [ ] `IntoParallelIterator`
- [ ] `IntoParallelRefIterator`
- [ ] `IntoParallelRefMutIterator`
- [ ] `IndexedParallelIterator`
- [ ] `ParallelExtend`
- [ ] `ParallelIterator` will be finished by #511 
- [ ] `ParallelSlice`
- [ ] `ParallelSliceMut`
- [ ] `ParallelString`

(#512 does add documentation to some of these, but not examples.)

Also, the iter functions are in good shape except for `iter::split()`.

**Comment by cuviper** [comment]
All checked!
