### ISSUE TITLE
doc: Structures/types should all be documented

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#422]
For iterators and such they can likely just include some documentation as to where they're constructed (if not otherwise obvious) and what they're used for, rayon probably doesn't need a doc example per structure

**Comment by Hittherhod** [comment]
I added documentation for Zip, Rev, IntoParallelIterator, IntoParallelRefIterator, and IntoParallelRefMutIterator. I've got it on a local branch on my machine. How can I push it up?

**Comment by cuviper** [comment]
@Hittherhod you need to fork the repository on github, push your local changes to a branch in your fork, and then open a pull request here.  [Here's a tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) that looks pretty thorough.

**Comment by Hittherhod** [comment]
Thanks. I just submitted my changes in a pull request. #450

**Comment by nikomatsakis** [comment]
Once missing docs is enabled, we'll call this one closed.

**Comment by nikomatsakis** [comment]
This is done.
