### ISSUE TITLE
Configuration uses `self` instead of `&mut self`

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#425]
I think (although I could be wrong) nowadays the builder guidelines recommend using `&mut self` rather than `self`-by-value, so it may be worth considering for this type!

**Comment by cuviper** [comment]
We'd have to make a breaking change in rayon-core for this, or else wrap it with the different style for `rayon` like you suggested elsewhere.

**Comment by alexcrichton** [comment]
Indeed yeah it's up to you really, if y'all don't think it's worth it to move to `&mut self` then feel free to close!

**Comment by nikomatsakis** [comment]
I don't know that it's worth it. This builder is used in a pretty limited capacity.

**Comment by burdges** [comment]
[_"Under the rubric of making easy things easy and hard things possible, all builder methods for a consuming builder should take and returned an owned self."_](https://aturon.github.io/ownership/builders.html)

**Comment by cuviper** [comment]
In @burdges's link, while it says non-consuming builders are preferred, it does recommend all methods consume `self` when the final build is consuming -- as ours is.  Plus, we don't want to break rayon-core anyway, so I'm closing this one.
