### ISSUE TITLE
Add an unsafe method to rayon-core to enable `rayon-futures`

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#428]
It sounded like rayon, which ideally hits 1.0 soon-ish, will reach 1.0 before the `futures` crate but the rayon 1.0 release shouldn't publicly depend on unstable crates. In that sense it sounds like a separate crate, `rayon-futures`, is the way to go for now, but needs support in `rayon-core`

**Comment by cuviper** [comment]
#436 made rayon-futures a separate crate, but we still need to decide if we like that core interface.
(still under `--cfg rayon_unstable` for now)

**Comment by cuviper** [comment]
That code was removed in #716.
