### ISSUE TITLE
rayon::spawn should document the lack of return value

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#431]
This seemed to be at least very similar to `std::thread::spawn`, but it may be worth documenting why a return value isn't exposed here. (and recommend using the rayon-futures crate if that's what you need)

**Comment by Hittherhod** [comment]
I'd be willing to tackle this.

**Comment by Hittherhod** [comment]
Just to be clear, there is already a section that says this function assumes the closure is executed purely for its side effects and that to compute a value, the user might want to consider `spawn_future`. What additional documentation do you think would be helpful in this case?

**Comment by Hittherhod** [comment]
I'm still a little unclear what you mean by "why a return value isn't exposed here". Is it because the thread is placed into the global or static threadpool and thus can't be safely accessed? Or is it because the spawned thread is completely detached from its parental stack frame?

**Comment by cuviper** [comment]
The docs already address the `'static` requirements regarding the stack frame, but that's no different than `std::thread::spawn`.  I guess the question is why we don't have a `JoinHandle`, and I don't recall the reason for this -- @nikomatsakis?
