### ISSUE TITLE
Vec::truncate_par

### ISSUE THREAD

**Issue by njaard** [rayon-rs/rayon#490]
I have some code that truncates a large Vec and I found that the `drop`s were very costly. It would be nice to see a `truncate_par` in Rayon.

I use the following `unsafe` code to drop the tail of the vec in parallel:

    self.par_iter_mut()
        .skip(len)
        .for_each(|r| std::ptr::drop_in_place(r));
    let n = std::cmp::min(self.len(), len);
    self.set_len( n );

**Comment by cuviper** [comment]
Note that `skip` is not as efficient as it could be (#352), and your example also has a problem with panic safety.  If any of those `drop`s panic, then the vector's length will not be adjusted, and the vector's own `drop` will try to re-drop some items!

You can see how `rayon::vec::IntoIter` deals with this [here](https://github.com/rayon-rs/rayon/blob/5b11364fed9ae23d21521ea7cb56a53f6f0d61e6/src/vec.rs#L55-L61).

Parallel `truncate` seems kind of niche to me -- we should think if there may be a more general approach.  A parallel [`drain`](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.drain) would let you write something like `vec.par_drain(len..)`, but we need stable `RangeArgument` to allow different range types.  (Or we could create our own equivalent to `RangeArgument`.)

**Comment by njaard** [comment]
I agree that a parallel `drain` is a better and more general solution.
