### ISSUE TITLE
IndexedParallelIterator::len requires mutable borrow

### ISSUE THREAD

**Issue by wagnerf42** [rayon-rs/rayon#491]
Is there any reason for the mutable borrow ?
that's kind of unusual. are there some hidden costs ?

**Comment by cuviper** [comment]
I believe @nikomatsakis just wanted it to be more flexible for the implementer, but I'm not sure if any of our current implementations actually take advantage of this.

Is it a problem for you?  It should only be a burden for the caller, and I think typically only rayon internals will be calling it.  Do you call it yourself?

**Comment by nikomatsakis** [comment]
@cuviper is correct, I thought it would be better if the implementor was able to do mutation.

**Comment by nikomatsakis** [comment]
Discussing with @cuviper, we decided that -- for parity with iterator -- we might as well make it `&self`.

**Comment by cuviper** [comment]
Fixed by #514.
