### ISSUE TITLE
Implement step_by

### ISSUE THREAD

**Issue by hherman1** [rayon-rs/rayon#494]
I believe this should be parallelizable? The iterator is currently in nightly rust:

https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.step_by

**Comment by cuviper** [comment]
It should be possible, yes.  I think I'd prefer to wait for `Iterator::step_by` to stabilize though, so we can make sure to match its signature.

**Comment by lu-zero** [comment]
The iterator is now in stable since a while :)

**Comment by gbip** [comment]
This would be a very useful feature :smile:

**Comment by emmanuelantony2000** [comment]
Can i try to implement it?

**Comment by cuviper** [comment]
Go for it!

**Comment by FlyingCanoe** [comment]
I have created a pull request adding this future, but It depend on std StepBy being a double ended iterator. This trait as bean stabilise in rustc 1.38. Does bumping the minimal rustc version is acceptable for this future?

**Comment by cuviper** [comment]
I don't think we should bump the MSRV for this feature. We can either implement our own version of the `StepBy` iterator, or add a build script which detects support to set a `cfg` (so it wouldn't be available at all earlier). Use [autocfg](https://crates.io/crates/autocfg) if you go for a build script, where you can probe an expression like `(0..10).step_by(2).rev()`.

**Comment by Coder-256** [comment]
I think that this #726 was supposed to close this. :)

**Comment by cuviper** [comment]
Yes, thanks!
