### ISSUE TITLE
Cancelling on Result Err

### ISSUE THREAD

**Issue by PSeitz** [rayon-rs/rayon#496]
Hi I have a function, which returns an Result<(), Error>. I want to early return on errors.

I saw in [result.rs](https://github.com/rayon-rs/rayon/blob/master/src/result.rs#L85-L117)  something, that uses while_some may be the right method here, although I don't know how to use that. I couldn't find something in the documentation.

Also a while_ok method would probably be nice.

**Comment by PSeitz** [comment]
Thanks, I wasn't aware of the type hint, but seems pretty obvious in hindsight.

**Comment by WilliamVenner** [comment]
`while_ok` would allow you to have a `filter_map` that stops depending on a predicate.

`while_some` does not work with `filter_map` for obvious reasons 😁

**Comment by YuriGeinishO** [comment]
Hello, I'm doing
```rust
fn main() -> anyhow::Result<()> {
    0..123123
        .into_par_iter()
        .map(|num| {
            /* something with lots of foo()? */
            println!("Hi from {num}");
            anyhow::Ok(())
        })
        .collect::<Result<Vec<_>, _>>()?
    ;
    Ok(())
}
```

And then running with `cargo run | head -n 10`. So when Bash closes the pipe to `head` after 10 successful printlns, errors start getting throw for every `println` with the broken pipe error, as expected. However, this doesn't seem to stop Rayon, as it keeps dumping panic errors on stderr non-stop.

What am I doing wrong please?

**Comment by cuviper** [comment]
@YuriGeinishO the `println!` macro doesn't _return_ any errors, even though it reports them. Try something like this:

```rust
use std::io::{stdout, Write};
// ...
            writeln!(stdout(), "Hi from {num}")?;
```
