### ISSUE TITLE
Implement `chunks`

### ISSUE THREAD

**Issue by gnzlbg** [rayon-rs/rayon#501]
Right now if I have a slice I can do:

```rust
slice.par_chunks(500)....
```

but if I have an iterator I can't chunk it:

```rust
(0..100000).par_chunks(500)... // Error
(0..100000).into_par_iter().chunks(500).... // Error
```

So I end up needing to work around this as:

```rust
let indices: Vec<_> = (0..100000).collect(); // :(
indices.par_chunks(500)... // Works
```

which is horrible.

**Comment by cuviper** [comment]
Standard iterators don't have `chunks` either. How do you imagine this should work?

**Comment by gnzlbg** [comment]
Chunks is part of itertools .

**Comment by cuviper** [comment]
Ah, ok... for reference: https://docs.rs/itertools/0.7.4/itertools/trait.Itertools.html#method.chunks

**Comment by tmccombs** [comment]
I've started working on this.

**Comment by gnzlbg** [comment]
itertools::chunks is based on itertools::group_by, so it might be better to do the same here.

**Comment by cuviper** [comment]
I doubt that the general `group_by` is possible here, as it seems inherently sequential.  Imagine, what if the entire iterator resolved to one large group?  There's no way to know without evaluating the `key` function in order.

But we can know exactly how many items will go into chunks, at least on `IndexedParallelIterator`, which allows us to split it in parallel.
