### ISSUE TITLE
Working with lazy iterators?

### ISSUE THREAD

**Issue by ysimonson** [rayon-rs/rayon#518]
I'm trying to implement parallel map/reduce that operates over values lazily fetched from a database. I cannot load all of the records from the database at once because they may consume more memory than is available.

It seems someone else had the [same question on SO](https://stackoverflow.com/questions/35863996/cannot-use-rayons-par-iter), though as far as I can see, the accepted solution will load everything in-memory unless you reimplement all of `ParallelIterator`.

Is there a way to do this in rayon? I can try to hand-roll something out myself, but hoping that that I can instead leverage all of rayon's greatness for this!

**Comment by anderejd** [comment]
Take a look at this: https://github.com/QuietMisdreavus/synchronoise
I have not tried the library yet but I implemented a similar thing in a way less polished state that worked ok:
https://github.com/anderejd/sgiter/blob/master/src/lib.rs (no docs, only an early experiment, try synchronoise instead)

I would like rayon to support any Iterator where the elements are Send.

**Comment by cuviper** [comment]
Parallelizing any general `Iterator` is issue #46.

The closest lazy way I know right now is if you can start with a base parallel iterator like just indexes, and then `map` to the fuller records as they are accessed.  But I guess repeated random-access indexing of a database is not a good idea.

If you know the number of records there will be, and the amount processing on each will outweigh the cost of synchronization, you could wrap a mutex around your database cursor and use `map` to get the next record.  Something like `(0..num_records).into_par_iter().map(|_| cursor.lock().unwrap().next())`.  This won't preserve the original order though, which could matter if you need a non-commutative `reduce`.

Another option I often recommend is to group your data into chunks that *do* fit in memory, so you're working in phases.  Read some data, parallelize, read more, parallelize, etc.

**Comment by ysimonson** [comment]
Cool, thanks for the pointers @anderejd and @cuviper! I'll close this out and watch #46.
