### ISSUE TITLE
No implementation for std::collections::hash_set::Intersection

### ISSUE THREAD

**Issue by naftulikay** [rayon-rs/rayon#524]
A `std::collections::hash_set::Intersection` is produced from two `std::collections::HashSet`s and is composed of elements that exist both in collection `a` and collection `b`.

I would like to be able to iterate over this object so I am seeking to implement `rayon::iter::IntoParallelIterator`, but I am not able to find a good starting point. I am more than happy to contribute code to Rayon, how can I contribute to adding this support?

**Comment by cuviper** [comment]
We can't directly parallelize `Intersection`, as we have no access to its internals.  But you can approximate this in a couple ways:

```rust
// Perform the same comparison that `Intersection` does itself.
// (note: `a.par_iter()` internally has to serially collect all references from `a` first)
a.par_iter().filter(|x| b.contains(x)) ...

// Collect the `Intersection`, then use that in parallel
a.intersection(&b).collect::<Vec<_>>().into_par_iter() ...
```

Or, you can use [rayon-hash](https://docs.rs/crate/rayon-hash/0.2.0)'s `HashSet`, which has a [`par_intersection`](https://docs.rs/rayon-hash/0.2.0/rayon_hash/struct.HashSet.html#method.par_intersection) that *doesn't* have to do any collection up front!

We could consider adding extensions like `par_intersection` to the standard `HashSet`, but that would still have to do a `collect()` in one of the ways mentioned above.  There's no universal answer which way would be better -- depending on the cost of lookups, how many intersections are expected, and what you plan to do with them -- which makes me hesitate to add this.

**Comment by cuviper** [comment]
Generally I'd point you to [plumbing/README.md](https://github.com/rayon-rs/rayon/blob/master/src/iter/plumbing/README.md) to learn how to implement, and suggest looking at some of the types we already have done.  But I don't think `Intersection` is feasible.

**Comment by naftulikay** [comment]
@cuviper Thank you so much for your response! Thanks for pointing me in the right direction. You can close this if you'd like.

**Comment by cuviper** [comment]
OK - hopefully we'll see some other contribution from you! :)
