### ISSUE TITLE
iter::split() is awesome, perhaps the docs should advertise it more

### ISSUE THREAD

**Issue by HadrienG2** [rayon-rs/rayon#537]
One thing which I love about rayon is its well thought-out layered design. High-level and low-level tasks are all pretty well taken care of in the API and the docs, and it is easy to start at the abstraction layer that fits your task best and work from there.

In this context, one excellent ingredient is iter::split(). It simplifies the work of creating a custom parallel iterator greatly, thusly making it easy to handle some computation styles which are not natively supported by rayon yet, such as index sensitive computations on 2D images.

However, I think it does not get enough coverage in the (beautifully revamped) docs currently. Neither the front page nor the "iter" module description talk about it, you need to scroll all the way to the end of iter's module contents in order to learn that it exists. Perhaps you should mention this option before taking people to the plumbing module, as it is often a nice middle-ground between both.

**Comment by cuviper** [comment]
It's sort of a chicken-and-egg -- it's not used much, so we don't talk about it, so most people don't know about and don't use it, so...

But as you're someone who did discover it, and you're apparently a fan, can I interest you in writing such an advertisement for the docs?

**Comment by HadrienG2** [comment]
How about this? https://github.com/rayon-rs/rayon/pull/539
