### ISSUE TITLE
Interest in moving to rust-lang or rust-lang-nursery?

### ISSUE THREAD

**Issue by bstrie** [rayon-rs/rayon#543]
About a year ago the question came up about providing "blessed" building blocks for concurrency as a part of rust-lang-nursery, for which Niko had some thoughts: https://internals.rust-lang.org/t/scoped-threads-in-the-nursery-maybe-with-rayon/4942 . Given that Rayon has just reached 1.0, I figure now's a good time to restart that discussion. In particular I'm curious whether any of the comments there regarding Rayon's configurability/generality/interoperability are still relevant in the post-1.0 design. Any thoughts?

**Comment by cuviper** [comment]
I think it's OK for de facto standard crates to live outside of rust-lang -- like serde, for instance.  It might even be _better_ to break the notion that crates should be "blessed" in this way.

**Comment by cuviper** [comment]
The trend seems to have shifted the other way, e.g. `rand` moved to @rust-random, so I think we're fine here in @rayon-rs.
