### ISSUE TITLE
Does Rayon eventually plan to auto-vectorize code to SIMD?

### ISSUE THREAD

**Issue by egilburg** [rayon-rs/rayon#546]
Not really an "issue", I just didn't know where else to ask the question. Perhaps it could be part of the FAQ.

I think I read somewhere before that Rayon could potentially deal with SIMD vectorization behind-the-scenes (e.g. user doesn't need to write explicit SIMD code, just keep using `par_iter` etc.), to make a more efficient "micro" step (the macro step of multiple workers is only beneficial at batch sizes above a certain amount, while vectorization could happen inside the batch).

But I'm not sure if it's just a rumor or actually a future goal of Rayon, so asking here.

The RFC to stabilize SIMD was just merged https://github.com/rust-lang/rfcs/pull/2325 so I thought it's a good time to ask this.

**Comment by eddyb** [comment]
LLVM already auto-vectorizes batched computation, so typical usage of rayon *should* be involving SIMD a lot of the time. It's harder for a library to do anything useful and automatic here.

**Comment by cuviper** [comment]
Yeah, Rayon itself doesn't have any real visibility into what the user code is doing.  Maybe we'll find ways that we could restructure loops for rustc+LLVM to do their job better -- we already try to lower to simple iterators as much as possible.

**Comment by lnicola** [comment]
@egilburg You might want something like https://crates.io/crates/faster.

**Comment by cuviper** [comment]
I think this is answered, but feel free to follow up!
