### ISSUE TITLE
Add support for parallel iteration over `&[&Path]` and `&[PathBuf]`

### ISSUE THREAD

**Issue by jjpe** [rayon-rs/rayon#549]
Consider the following code:

    fn foo(filenames: &[PathBuf]) -> MapResult<()>  {
        for filename in filenames.par_iter() {
            self.process(filename)?;
        }
        Ok(())
    }

This fails to compile with the error
````
error[E0277]: the trait bound `rayon::slice::Iter<'_, std::path::PathBuf>: std::iter::Iterator` is not satisfied
   --> src/lib.rs:187:25
    |
187 |         for filename in filenames.par_iter() {
    |                         ^^^^^^^^^^^^^^^^^^^^ `rayon::slice::Iter<'_, std::path::PathBuf>` is not an iterator; maybe try calling `.iter()` or a similar method
    |
    = help: the trait `std::iter::Iterator` is not implemented for `rayon::slice::Iter<'_, std::path::PathBuf>`
    = note: required by `std::iter::IntoIterator::into_iter`

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0277"
error: Could not compile `sbr-mapping-core`.
warning: build failed, waiting for other jobs to finish...
error[E0277]: the trait bound `rayon::slice::Iter<'_, std::path::PathBuf>: std::iter::Iterator` is not satisfied
   --> src/lib.rs:187:25
    |
187 |         for filename in filenames.par_iter() {
    |                         ^^^^^^^^^^^^^^^^^^^^ `rayon::slice::Iter<'_, std::path::PathBuf>` is not an iterator; maybe try calling `.iter()` or a similar method
    |
    = help: the trait `std::iter::Iterator` is not implemented for `rayon::slice::Iter<'_, std::path::PathBuf>`
    = note: required by `std::iter::IntoIterator::into_iter`

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0277"
error: Could not compile `sbr-mapping-core`.

To learn more, run the command again with --verbose.

````

Could support for `&[&Path]` and `&[PathBuf]` be added? AFAICT I can't do it from my own crate.

**Comment by cuviper** [comment]
The problem is not with `Path`, but that you're trying to use a parallel iterator in a `for` loop, which only takes a regular `Iterator`.  We would have to be integrated in the compiler to directly parallelize `for` loops.

Instead you should write this using `for_each`, at least when there are not early exits.  Since you're using the `?` operator, you can instead `collect` a result, like `filenames.par_iter().map(|f| process(f)).collect()`.  This will infer the `Result` type if you return it directly; otherwise you might need `collect::<MapResult<()>>()?`.

**Comment by jjpe** [comment]
Indeed, your `.map` suggestion works, but with a caveat I don't think I understand: why does the map call force the enclosing method's enclosing type (a trait called `Processor`) to have Sync as a supertype?

**Comment by cuviper** [comment]
> Is it because the closure in the map could in principle access the data in `self`,

If the closure captures `self`, then yes, the restriction applies to the whole of `Self`.  If you really only need some subset of the fields which are easier to make thread-safe, then you can bind those references to locals first, and use just those parts in the closure.

**Comment by jjpe** [comment]
I see. Thank you for the help, it is most useful.
I'll close this issue now, as my problem is effectively solved.
