### ISSUE TITLE
Ordering question

### ISSUE THREAD

**Issue by jjpe** [rayon-rs/rayon#551]
I was just wondering: Do the Rayon parallel iterators preserve ordering?
For example, if I have `vec![obj1, obj2, obj3].par_iter().map(|o| { operation_on(o)  })`, can I assume that the resulting iterator has the corresponding map results in the same order as in the `vec!`?

**Comment by cuviper** [comment]
Yes.  Your `operation_on` will be called in parallel, out of order, but if you have something like `collect` after that, it will still store the results in the original order.

**Comment by jjpe** [comment]
That's awesome, thanks!

**Comment by KarelPeeters** [comment]
For people coming here from google and ending up very confused (like me), this is not a universal guarantee, not everything in rayon is order-preserving, for example `par_bridge` does not preserve it.

See #669 or the the [ParallelBridge](https://docs.rs/rayon/1.5.1/rayon/iter/trait.ParallelBridge.html) docs.
