### ISSUE TITLE
Chars does not implement IndexedParallelIterator#enumerate

### ISSUE THREAD

**Issue by dbkaplun** [rayon-rs/rayon#559]
[Playground](https://play.rust-lang.org/?gist=fbfd4660501e9807394a10119555f318&version=stable)

It would be great if I could use `"foobar".par_chars().enumerate()`.

Thanks for considering!

**Comment by cuviper** [comment]
Unfortunately, since utf8 is variable length, indexing characters can only be done serially.  However, we could do a parallel version of `char_indices`, which provides the *byte* index with each character.  (This still will not be an `IndexedParallelIterator`.)
