### ISSUE TITLE
Add support for RangeInclusive 

### ISSUE THREAD

**Issue by shepmaster** [rayon-rs/rayon#572]
Rust 1.26 stabilizes [`RangeInclusive`](https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html) but none of its methods or fields. However, I believe you could hack it with `next()` and  `next_back()` / `last()` (yuck).

**Comment by cuviper** [comment]
The hack seem ok, although we'll have to be careful about empty and singleton ranges.

We can only implement `IndexedParallelIterator` for `i8`, `u8`, `i16`, and `u16`, just as those are the only ones that implement `ExactSizeIterator`.  e.g. `0..=usize::MAX` would overflow a `usize` length.  The rest can still implement unindexed `ParallelIterator` just like we do for 64-bit ranges.

We'll have to guard this with a feature flag or a build-script `cfg` to avoid bumping required rustc.

**Comment by hellow554** [comment]
I would love to see this. What is the status/blocker on this?

**Comment by cuviper** [comment]
STATUS: Just need someone to get around to it. :slightly_smiling_face:

**Comment by Walther** [comment]
https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html#method.end

Am I reading this correctly - 1.27 onwards the `start` and `end` methods are standardized even for the inclusive ranges, and hence could be used in rayon?

Regarding being careful about empty and singleton ranges, there seems to be a recommendation for using the `is_empty()` method. However, that's still labeled as nightly.

**Comment by cuviper** [comment]
@Walther I had a local branch where I started working on this, which I just pushed here:
https://github.com/cuviper/rayon/tree/range-inc

TBH I forget where I was with this, but at least it builds. :sweat_smile:  Looks like I was just cloning the range to query `next()` and `next_back()`, which sounds bad but is probably fine with primitive integers.  That should deal with empty ranges well too.  If you care to review, that would be nice.

**Comment by phungleson** [comment]
Hey @cuviper I took a look at [your changes](https://github.com/cuviper/rayon/commit/855070e88c1605ab6e9caadaee4a4c91f13f445f).

I am interested in getting this over the line if you don't work on this anymore, hope you still provide some guidance :).

**Comment by cuviper** [comment]
See #647 -- I simplified it by just forwarding to `range::Iter`.
