### ISSUE TITLE
Dispatching to a second pool from a job in one pool is buggy

### ISSUE THREAD

**Issue by staktrace** [rayon-rs/rayon#588]
```
extern crate rayon;

use std::sync::Arc;
use std::{thread, time};

fn main() {
    let pool = Arc::new(rayon::ThreadPoolBuilder::new().num_threads(1).build().unwrap());
    let pool2 = Arc::new(rayon::ThreadPoolBuilder::new().num_threads(1).build().unwrap());
    for x in 1..10 {
        let pool2_c = pool2.clone();
        pool.spawn(move || {
            println!("start job {}", x);
            pool2_c.install(move || {
                thread::sleep(time::Duration::from_secs(1));
            });
            println!("end job {}", x);
        });
        thread::sleep(time::Duration::from_millis(20));
    }
    thread::sleep(time::Duration::from_secs(12));
}
```

I would expect the spawned jobs to run one at a time, because the pool they're spawned into has only one thread. i.e. the output should be something like:

```
start job 1
end job 1
start job 2
end job 2
...
```

However, the actual output I get is:

```
start job 1
start job 2
...
start job 9
end job 9
end job 8
...
end job 1
```

which means the spawned tasks are running concurrently. This makes no sense to me. Note that if I do 1-second sleep inside the spawn task directly, instead of installing it into pool2, then I get the expected behaviour.

**Comment by mstange** [comment]
This output order doesn't necessarily mean that the jobs are running concurrently, they could also be running in a nested fashion on the same thread. E.g. the call to `pool2_c.install` might start executing pending work of the pool that owns the current thread.

**Comment by cuviper** [comment]
This is intentional, per #449, to make sure that invoking pools in a circle (A -> B -> A) won't deadlock.

I can see how your case is surprising, but the way I would think of `install` is that it blocks the current thread of execution in an abstract sense (the job is blocked), but the underlying thread pool is not blocked.

Does that semantic work for you?  For your example, if you really wanted those jobs to be executed in order, I would just move the `for` loop into the `spawn` so it's explicitly sequential.  Of course, I'm sure your real use case where you noticed this is more complicated...

**Comment by staktrace** [comment]
Ok, that makes sense. I'll close this issue. I can probably figure out how to update my original code to work with this semantic.

**Comment by bholley** [comment]
To expand upon this - I think the bug as filed was basically expecting the thread pool to provide additional guarantees when the number of threads was specified as 1. In Gecko terms, you wanted AbstractThread/nsISerialEventTarget [1]. But Rayon doesn't make those guarantees (considering the number of OS threads to be an implementation detail), and instead offers the semantics of nsIEventTarget/nsIThreadPool.

So it sounds like you want something like TaskQueue [2], which provides serial semantics on top of an underlying thread pool. It's conceivable that something like that could be built on top of (or into) rayon.   In C++/XPCOM these semantics are critical for thread-safety, whereas they obviously aren't in Rust/Rayon. But it sounds like there still may be some value there for maintaining program invariants, so it's worth thinking about.

[1] https://searchfox.org/mozilla-central/source/xpcom/threads/AbstractThread.h
[2] https://searchfox.org/mozilla-central/source/xpcom/threads/TaskQueue.h
