### ISSUE TITLE
Gain deeper control of `split`?

### ISSUE THREAD

**Issue by termhn** [rayon-rs/rayon#593]
I want to build a parallel iterator over a 2d domain for use in a ray tracer. `split` looks great for this, except that I want finer grained control over how the work is split. In my case, I want to be able to define the "tile size" that split will attempt to divide the data into (with possibly some smaller tiles based on whether the tile size divides evenly into the overall data size). As far as I understand it, `split` will attempt to split a non-deterministic number of times to try to optimize for best performance like other parallel iterators. For a ray tracer this is not necessarily desired behavior because the complexity of work for different parts of the scene is possibly vastly different, so it is often more efficient to split into smaller pieces than would normally be optimal, so that threads are not left idle while a more complex tile is being completed. Is it possible to do something like this with rayon? I could use `scope` for it, but thought I'd ask if there was a better way.

**Comment by cuviper** [comment]
I don't know if we can provide deeper control in a generic way.  Or rather, the deeper control is for you to implement `ParallelIterator` and `IndexedParallelIterator` yourself, and then you can apply a `with_max_len` policy as you see fit.  Or maybe implement your own `par_tiles()` API similar to our `par_chunks()` that produces a `ParallelIterator` of a chosen size.

> As far as I understand it, `split` will attempt to split a non-deterministic number of times to try to optimize for best performance like other parallel iterators.

Yes, it's adaptive.  We start by splitting proportionally to the number of threads.  When work gets stolen, we split it even further, as a heuristic that the busy worker may have a long-running job on its hands already.  That dynamically hits a limit when threads stop stealing from each other, then they're sufficiently busy.

> For a ray tracer this is not necessarily desired behavior because the complexity of work for different parts of the scene is possibly vastly different, so it is often more efficient to split into smaller pieces than would normally be optimal, so that threads are not left idle while a more complex tile is being completed.

That kind of imbalanced work is exactly what the adaptive splitting is meant to help with.  I suppose you could still get unlucky if the very first unstolen piece of work happened to be particularly complex though.

> I could use `scope` for it, but thought I'd ask if there was a better way.

Dropping down to manual `join` or `scope`+`spawn` calls is perfectly reasonable, if you don't really need the rest of the iterator API.

**Comment by termhn** [comment]
@cuviper thanks for the response; very helpful!

**Comment by cuviper** [comment]
You're welcome.  Feel free to reopen this if you have further questions, or start a new issue if unrelated.
