### ISSUE TITLE
Have a crate option to disable rayon completely for testing

### ISSUE THREAD

**Issue by pedrocr** [rayon-rs/rayon#608]
Often when benchmarking slow code the perf output is full of rayon internals. It's also the case when benchmarking crash code and getting a stack trace. It would be nice if there was a crate option that would just disable rayon completely and have the iterators be a simple sequential implementation. That way a test version with just sequential code could be easily created to test crashes and performance.

**Comment by bluss** [comment]
This is also discussed in issue: #591

**Comment by pedrocr** [comment]
Yep, that's pretty much the same thing, I just hadn't found it when I submitted this. Closing this one.
