### ISSUE TITLE
Question: are Rayon constructs composable (nesting)

### ISSUE THREAD

**Issue by matsbror** [rayon-rs/rayon#613]
This is more of a question than an issue. Given that Rayon constructs spawn tasks for work-stealing, I assume that they can be nested arbitrarily. Can someone confirm if this is the case?

**Comment by wagnerf42** [comment]
hi, it's not too bad.
decompositions into tasks is dynamic and you will eventually get p**k log(n) tasks created for k levels of nesting (p your threads number).
i am actually working on a (hopefully) better way to nest computations. If you have interesting use cases for nested parallelism i'd be very happy if you could share them with me.

**Comment by cuviper** [comment]
Yes, it should be perfectly fine to nest rayon calls.  Even the parallel iterators themselves just come down to nested joins.  The only constraint is that you don't overflow the stack, just like any other recursion.

If you know there's already a lot of parallelism around a computation, it may not be beneficial to divide into further tasks that will just execute locally.  We try to keep the task overhead low, but it's still not free, so you may need to experiment with what works best for your code.

**Comment by nikomatsakis** [comment]
Closing for now, as I think the question has been answered. Feel free to re-open!
