### ISSUE TITLE
Combined thread and async pool, with single returned collection?

### ISSUE THREAD

**Issue by SamuelMarks** [rayon-rs/rayon#624]
Common use case, I have a collection of URLs, which all need to be downloaded. The results should be stored in a collection of same size as input.

Simple, right? - Okay, let's get a little fancier with requirements. This time, `pub fn download` is in another `crate`, and the `const URLS: &'static [&'static str]` is passed through to the `download` function.

Here, I may use some heuristic, like given a collection of 10000000 URLs, chunk them into 10% buckets, and iterate over the collection of buckets using **`par_iter`**. Now, each bucket—containing 10% of total URLs—is handed over to mio which processes them asynchronously.

I know the size of the initial collection. I can guarantee the invariant that no two threads or async tasks will ever read or write the same element in the collection. Seeing as I have my own invariant, I guess I need `unsafe`? 🚧 

Finally, at the end of the function, once all the async tasks have finished—which also means the threads have concluded—it can return a constant sized + constant capacity + constant length collection, containing all the results of the URL requests.

Here is my current version, which just uses mio (no rayon), and containing the collection of URLs in the same crate (not passed into the function through an argument):

```rust
#![feature(const_slice_len)]

#[macro_use]
extern crate failure;

use mio::{Events, Poll};
use mio_httpc::{CallBuilder, Httpc, HttpcCfg, SimpleCall};

use failure::Error;

const URLS: &'static [&'static str] = &["http://detectportal.firefox.com/success.txt"];

fn do_call(htp: &mut Httpc, poll: &Poll, mut call: SimpleCall) -> Result<String, Error> {
    let mut buf: Option<String> = None;
    let to = ::std::time::Duration::from_millis(100);
    let mut events = Events::with_capacity(8);
    'outer: loop {
        poll.poll(&mut events, Some(to)).unwrap();
        for cref in htp.timeout().into_iter() {
            if call.is_ref(cref) {
                return Err(format_err!("Request timed out"));
            }
        }

        for ev in events.iter() {
            let cref = htp.event(&ev);

            if call.is_call(&cref) && call.perform(htp, &poll).expect("Call failed") {
                let (resp, body) = call.finish().expect("No response");
                println!("done req = {}", resp.status);
                for h in resp.headers() {
                    println!("Header = {}", h);
                }
                match String::from_utf8(body.clone()) {
                    Ok(s) => buf = Some(s),
                    Err(_) => {
                        return Err(format_err!("Non utf8 body sized: {}", body.len()));
                    }
                }
                break 'outer;
            }
        }
    }
    match buf {
        Some(s) => Ok(s),
        None => Err(format_err!("Empty response")),
    }
}

pub fn download<T>() -> Result<[String; URLS.len()], Error> {
    let poll = Poll::new().unwrap();

    let cfg = match HttpcCfg::certs_from_path(".") {
        Ok(cfg) => cfg,
        Err(_) => Default::default(),
    };
    let mut htp = Httpc::new(10, Some(cfg));

    let mut a = [String::from(""); URLS.len()];

    for i in 0..URLS.len() {
        println!("Get {}", URLS[i]);
        let call = CallBuilder::get()
            .url(URLS[i])
            .expect("Invalid url")
            .timeout_ms(10000)
            // .insecure_do_not_verify_domain()
            .simple_call(&mut htp, &poll)
            .expect("Call start failed");
        match do_call(&mut htp, &poll, call) {
            Ok(response_string) => a[i] = response_string,
            Err(e) => return Err(format_err!("{}", e)),
        }

        println!("Open connections = {}", htp.open_connections());
    }
    Ok(a)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        match download::<String>() {
            Ok(responses) => {
                for resp in &responses {
                    assert_eq!(resp, "success\n");
                }
            }
            Err(e) => panic!(e),
        }
    }
}
```

Is rayon the right tool for implementing what I'm envisioning, is there a better tool, or is my use-case so custom that I need to write this all by hand?

Thanks for your suggestions 🤕

**Comment by cuviper** [comment]
We have the experimental rayon-futures crate for async scenarios, and we plan to update that to the upcoming async+futures support in the compiler. But rayon is really intended for CPU-parallelism. If your workload is mostly IO-bound, you probably want [tokio](https://crates.io/crates/tokio), which has its own thread pool

**Comment by SamuelMarks** [comment]
Okay, thanks for your insights.
