### ISSUE TITLE
Parallel iterators should just fail early in case of panic instead of continuing to issue more workers

### ISSUE THREAD

**Issue by pedrocr** [rayon-rs/rayon#638]
When using a parallel iterator if a panic happens in one of the threads that doesn't stop more threads from being launched. This is a surprising behavior since in the equivalent sequential code the loop will terminate early because of the panic. This can lead to DoS in code like this:

```rust
extern crate rayon;
use self::rayon::prelude::*;

fn main() {
    let width  = 10;
    let height = 10;

    let mut out: Vec<u16> = vec![0u16; width*height];
    out.par_chunks_mut(width).enumerate().for_each(|(row, _line)| {
        panic!("panic at row {}", row);
    });
}
```

When `height` is very large it takes forever to issue panics for all the lines. I hit this when fuzzing a binary image format where a well crafted file would take advantage of this to force the code to go through the slow panic processing path a few million times and cause a DoS. The bug is introduced by the parallel iterator as the sequential code would bail at the first panic.

**Comment by pedrocr** [comment]
This on the other hand works as expected:

```rust
extern crate rayon;
use self::rayon::prelude::*;
use std::panic;

fn main() {
    let width  = 10;
    let height = 10;

    let mut out: Vec<u16> = vec![0u16; width*height];
    out.par_chunks_mut(width).enumerate().try_for_each(|(row, _line)| {
        panic::catch_unwind(|| panic!("panic at row {}", row))
    }).ok();
}
```

So the mechanism to abort early already exists for the `try_for_each` variant, it's just not used for panics in `for_each`.

**Comment by cuviper** [comment]
At the low level in `rayon-core`, where panics are caught and propagated, it doesn't know about parallel iterators or what jobs are related. It can only see a connection in that iterators use `join`, but we have explicitly [documented its panic behavior](https://docs.rs/rayon-core/1.4.1/rayon_core/fn.join.html#panics) like so:

> No matter what happens, both closures will always be executed. If a single closure panics, whether it be the first or second closure, that panic will be propagated and hence join() will panic with the same panic value. If both closures panic, join() will panic with the panic value from the first closure.

The implementation of `try_for_each` maintains a shared `AtomicBool` across all threads to track its completion state. I think that's too much synchronization to force on `for_each` and all other parallel iterators.

IMO, panics should be seen as an exceptional case, where we strive for safety and correctness, but don't necessarily worry about performance. If you're worried about DoS, I can imagine plenty of scenarios where bad input causes extraordinary processing time *without* any panic. Still, your custom solution with `panic::catch_unwind` seems appropriate if you want to be more defensive.

**Comment by nikomatsakis** [comment]
I wonder if we might add a kind of wrapper, sort of like `fuse`, that adds the panic propagation.

**Comment by nikomatsakis** [comment]
It seems plausible to do.

**Comment by pedrocr** [comment]
The behavior of join makes sense, I hadn't inferred from that the behavior of the iterator though. I had assumed that once enough panics had propagated (maybe one per thread in the pool at least) the iterator would abort. But that was with a mental model of a serial loop launching threads as they become available in the pool. I guess an iterator is instead conceptually `join(A, join(B, join (C...)))` and thus there's no point where a join has already returned with panic and further threads can stop being launched. Is there any downside to just aborting the second side of the join if the first side has already panic'ed and the second side is still waiting for a thread? Surely if you're already in a panic situation you're not depending on results from the second operation?

The `try_for_each` version works for the minimized test case but not for the actual code because the `catch_unwind` boundary limits what can be passed in to a closure. I've fixed the DoS by just limiting `height` to a reasonable value so at most this is now a small slowdown instead of an actual DoS. But since the behavior was surprising to me I thought I should report it.

It would still be nice to fix this somehow. If nothing else it makes debugging harder because you get a long list of repeat panics instead of just a few at most  If there's a simple way to add that check I'd be happy to benchmark it thoroughly in rawloader. It runs a bunch of threaded tight loops for all its decoders, so performance regressions here would be bad, and I already have everything setup to do meaningful tests:

http://chimper.org/rawloader-rustc-benchmarks/

**Comment by cuviper** [comment]
> Is there any downside to just aborting the second side of the join if the first side has already panic'ed and the second side is still waiting for a thread?

If we wanted to change our guarantees, yes, we could avoid starting the second side. You'd still be stuck if it already started though, so I'm not sure your DoS risk would be much reduced.

> Surely if you're already in a panic situation you're not depending on results from the second operation?

We don't even give you the result of the non-panicking part, but it may still be important for its effects.

> The `try_for_each` version works for the minimized test case but not for the actual code because the `catch_unwind` boundary limits what can be passed in to a closure.

You can assert its safety as long as you re-panic before any broken invariant might be visible. For example, here I have an atomic to short-circuit other work, then `resume_unwind` the guilty party.

```rust
    let quit = AtomicBool::new(false);
    out.par_chunks_mut(width).enumerate().try_for_each(|(row, _line)| {
        if quit.load(Ordering::SeqCst) {
            return None;
        }
        let result = panic::catch_unwind(AssertUnwindSafe(|| {
            panic!("panic at row {}", row)
        }));
        if let Err(payload) = result {
            quit.store(true, Ordering::SeqCst);
            panic::resume_unwind(payload);
        }
        Some(())
    });
```

But maybe we can find a nice API to wrap this concept, as @nikomatsakis suggests.

**Comment by pedrocr** [comment]
> If we wanted to change our guarantees, yes, we could avoid starting the second side. You'd still be stuck if it already started though, so I'm not sure your DoS risk would be much reduced.

It's a race but since panic unwind is not particularly fast once you filled your CPUs it will probably end sooner. But not ideal, I agree.

> We don't even give you the result of the non-panicking part, but it may still be important for its effects.

Right, my point was that if a part of the execution has already panic'ed you're unlikely to be relying on any effect from another part. Any thing sane you want to do there will almost surely require resetting to a sane state where everything has been thrown away. But maybe there are cases where that's not true.

A nice API would be great but unless I'm understanding something wrong this is actually enough:

```rust
extern crate rayon;
use self::rayon::prelude::*;
use std::panic;

fn main() {
    let width  = 10;
    let height = 10;

    let mut out: Vec<u16> = vec![0u16; width*height];
    match out.par_chunks_mut(width).enumerate().try_for_each(|(row, _line)| {
        panic::catch_unwind(panic::AssertUnwindSafe(|| panic!("panic at row {}", row)))
    }) {
        Err(_) => panic!("parallel execution panic'ed somewhere"),
        Ok(_)  => {},
    }
}
```

I can just use the handling of `try_for_each` to take care of stopping other threads and since I then launch a new panic everything is still safe, no?

Very preliminary testing shows this being either the same or even slightly faster than the previous code that only caught the panic much later in the stack. Maybe some optimization was unleashed from the panic handling happening in thread instead of having to cross threads. Will have to run a proper benchmark.

**Comment by cuviper** [comment]
> I can just use the handling of `try_for_each` to take care of stopping other threads and since I then launch a new panic everything is still safe, no?

I _think_ that's OK, though I'm not fully versed in `UnwindSafe` -- I try to catch and rethrow ASAP to avoid thinking about it. :slightly_smiling_face:

Instead of your "somewhere" panic, you could also `resume_unwind` your `Err` case to make use of the real payload. Or just `unwrap()` that result, depending on how you want the backtrace to look, since a backtrace from inside the threadpool is often confusing.

**Comment by pedrocr** [comment]
Ah, `resume_unwind` makes sense indeed. So wouldn't @nikomatsakis wrapper be just:

```rust
fn for_each_shortcircuits_panic<OP>(self, op: OP)
where OP: Fn(Self::Item) + Sync + Send {
  match self.try_for_each(|item| {
    panic::catch_unwind(panic::AssertUnwindSafe(|| OP(item)))
  }) {
    Err(e) => panic::resume_unwind(e),
    Ok(_)  => {},
  };
}
```

With a better name somehow. Although if this benchmarks as fine wouldn't it just replace `for_each`?

**Comment by cuviper** [comment]
I think the wrapper idea was that it would be part of the iterator chain, so it could work with anything, not just `for_each`.  e.g. `foo.into_par_iter().fuse().map(|_| ...).collect()`

> Although if this benchmarks as fine wouldn't it just replace `for_each`?

I doubt its performance would be so transparent. LLVM can get very clever with the optimization of tight loops, and I expect `catch_unwind` will throw a giant wrench in there. If `OP` represents a large amount of work on each item, that overhead probably won't matter, but that's something the programmer should evaluate.

**Comment by pedrocr** [comment]
The filter does look good. I'll try and run some proper benchmarks.

**Comment by cuviper** [comment]
Here's another version without explicitly catching anything:

```rust
struct Quitter<'a>(&'a AtomicBool);

impl Drop for Quitter<'_> {
    fn drop(&mut self) {
        self.0.store(true, Ordering::SeqCst);
    }
}

fn for_each_shortcircuits_panic<I, OP>(iter: I, op: OP)
where
    I: ParallelIterator,
    OP: Fn(I::Item) + Sync + Send,
{
    let quit = AtomicBool::new(false);

    iter.try_for_each(|item| {
        if quit.load(Ordering::SeqCst) {
            // There was already a panic somewhere
            None
        } else {
            // If we panic, the guard will set the bool on drop
            let guard = Quitter(&quit);
            op(item);

            // Otherwise forget the guard to leave the bool alone
            std::mem::forget(guard);
            Some(())
        }
    });

    // We'll never see quit==true; when it's set, we also resume the panic
    assert!(!quit.into_inner());
}
```

**Comment by pedrocr** [comment]
Cool. But isn't this now using two guard variables? One explicit and the other inside `try_for_each`?

**Comment by cuviper** [comment]
Yeah, it's redundant. In a true iterator adaptor we can do better.

**Comment by pedrocr** [comment]
At least for my usage the `catch_unwind` inside the loop and `resume_unwind` outside is a very slight performance improvement:

http://scratch.corujas.net/rayon-iterator-panic-bench/

It's only 0.2-0.3% in total but some uncompressed formats (very fast inner loops) got up to 12% improvements:

http://scratch.corujas.net/rayon-iterator-panic-bench/version-try.html

That may mean I shouldn't be threading those at all, now that they're so fast. But somehow the panic catching actually improved the speed. Optimizing compilers are strange beasts I guess. The results are not just random variation as `base` and `base2` are the same exact binary just to show what the natural variability of the test is. Each benchmark was ran 15 times and the median taken so noise was pretty well excluded.

**Comment by cuviper** [comment]
I think we're now set with the available `panic_fuse()`. Users have the option to propagate panics sooner, at the cost of some extra synchronization.
