### ISSUE TITLE
Getting thread number

### ISSUE THREAD

**Issue by GuillaumeGomez** [rayon-rs/rayon#639]
To avoid reallocating a big at each turn inside my parallel iterator, I'd like to instantiate a big `Vec<Vec<_>>` outside so I can then just send the corresponding `Vec` into my function. However, it doesn't seem like I can get the current thread number since it requires to have a `ThreadPool` object and there is no way to have one. Maybe I'm missing something though...

I see two ways of having access to this information:
 * Adding a function `current_thread_index` which doesn't need to be run on a `ThreadPool`
 * Providing a closure which pass the `ThreadPool` object (or directly the thread number)

What do you think of this?

**Comment by cuviper** [comment]
> Adding a function `current_thread_index` which doesn't need to be run on a `ThreadPool`

Ah, `rayon-core` does have this, but we neglected to re-export it in `rayon`.
https://docs.rs/rayon-core/1.4.1/rayon_core/fn.current_thread_index.html

Care to open a PR?

**Comment by GuillaumeGomez** [comment]
No problem.
