### ISSUE TITLE
Why ist par_iter slower than iter?

### ISSUE THREAD

**Issue by flosse** [rayon-rs/rayon#648]
I'm sorry for bothering but I just tried to take the [example of the README](https://github.com/rayon-rs/rayon#parallel-iterators-and-more) and expected that rayon is at least as fast as the std iterator.
What's happening here?

```rust
pub fn par_norm(v: &[f32]) -> f32 {
    let sum : f32 = v.par_iter().map(|&x|x*x).sum();
    sum.sqrt()
}

pub fn norm(v: &[f32]) -> f32 {
    let sum : f32 = v.iter().map(|&x|x*x).sum();
    sum.sqrt()
}

#[bench]
fn bench_par_norm(b: &mut Bencher) {
    let data = vec![20.0;2000];
    b.iter(|| {
        par_norm(&data)
    }); 
}
#[bench]
fn bench_norm_slice(b: &mut Bencher) {
    let data = vec![20.0;2000];
    b.iter(|| {
        norm(&data)
    }); 
}
```

```
test bench_norm_slice ... bench:       1,606 ns/iter (+/- 19)
test bench_par_norm   ... bench:      21,006 ns/iter (+/- 829)
```

**Comment by cuviper** [comment]
It's a matter of scale. Running in the threadpool does come with some overhead cost to performance, which I would informally estimate to have O(log n) complexity. You're only processing 2000 items with a very simple computation, so the serial iterator is already very fast, making parallelism too costly.

Here's what I get for increasing item counts:

```
# 2,000 items
test bench_norm_slice ... bench:       1,525 ns/iter (+/- 29)
test bench_par_norm   ... bench:      15,689 ns/iter (+/- 3,219)

# 20,000
test bench_norm_slice ... bench:      15,560 ns/iter (+/- 637)
test bench_par_norm   ... bench:      26,333 ns/iter (+/- 6,583)

# 200,000
test bench_norm_slice ... bench:     154,895 ns/iter (+/- 4,720)
test bench_par_norm   ... bench:      78,363 ns/iter (+/- 21,777)

# 2,000,000
test bench_norm_slice ... bench:   1,566,346 ns/iter (+/- 48,424)
test bench_par_norm   ... bench:     483,235 ns/iter (+/- 85,783)

# 20,000,000
test bench_norm_slice ... bench:  16,056,856 ns/iter (+/- 995,502)
test bench_par_norm   ... bench:   4,443,414 ns/iter (+/- 791,691)
```

I increased 10 times as many items each time, and the serial iterator showed the same 10x linear increase in time. The parallel iterator is clearly better than serial at 200k, and still didn't show linear growth until 2M->20M.

**Comment by flosse** [comment]
Thanks for your reply!
So the readme shouldn't say the following:

> Parallel iterators take care of deciding how to divide your data into tasks;
> **it will dynamically adapt for maximum performance.**

...because that doesn't seem to be the case!?

**Comment by Kobzol** [comment]
@flosse The most performant thing to do here would beto just run the iterator on a single core, but rayon has no way of knowing that the `map` content is so trivial. Even if you run the same loop and parallelize it using OpenMP in C/C++, you will not get a speedup. For parallelization to make sense, you need a large enough iterator and/or higher computational complexity per each item in the iterator. Parallelizing this loop simply makes no sense and that is also the reason why you don't see any speedup :slightly_smiling_face:

**Comment by cuviper** [comment]
Right -- rayon *does* dynamically adapt how it is dividing tasks, but it starts with the assumption that it makes sense to run in parallel in the first place. As a library, we can't tell how complicated your closure is, only that it has the right type signature.

**Comment by flosse** [comment]
Thank you guys!
My questions is answered now :)
Thanks for your time!
