### ISSUE TITLE
Question: Is it safe to use the global ThreadPool in test when using rayon?

### ISSUE THREAD

**Issue by fredpointzero** [rayon-rs/rayon#651]
Hi,

I am using rayon in my project and my first thought about writing tests is to use separate `ThreadPool` to avoid tests to interefere with each other. (With thread pool with 1 thread, to avoid CPU thread overload).

But I see that in the tests in the rayon repository uses the global ThreadPool.
So is it ok? When a panics occurs in one test, can it interfere with another test?

Bests!

**Comment by cuviper** [comment]
As long as you're OK with their execution interleaving in the thread pool, competing for resources, then yes it should be fine. Panics are caught and propagated to the original caller, without perturbing other tasks or the thread pool itself.

**Comment by fredpointzero** [comment]
Ok thanks for the answer!
