### ISSUE TITLE
Parallel DAG traversal

### ISSUE THREAD

**Issue by lpil** [rayon-rs/rayon#655]
Hello! Does Rayon have any support for parallel traversal of a DAG? Thank you.

**Comment by cuviper** [comment]
I think this is highly dependent on the DAG data structure, so there's not anything builtin to rayon.

If your DAG is actually a tree, only one incoming edge per node, then you can just use recursive `join` or `spawn` to traverse everything. For a more general DAG, you would need some kind of synchronized breadcrumbs for the nodes to avoid repeat visits.

If you don't actually care about traversal order, just that all nodes are visited, then you might be able to use a raw parallel iterator on your backing storage, e.g. a `Vec<Node>`.

**Comment by fredpointzero** [comment]
Actually, you can transform a DAG into a set of trees.
Once you have your forest, you can use parallel iterators and recursive fork-join to traverse the trees.

But you will have one issue about it: at some point two thread may try to run the same node, one can take the job and the other will have to "wait" it is completed.

However, using standard synchronization may end up into a deadlock, what you need is a "wait" that can execute local rayon tasks or steal rayon task between each condition check.
(Like #548)
