### ISSUE TITLE
Floating point non-determinism

### ISSUE THREAD

**Issue by yongqli** [rayon-rs/rayon#663]
I am currently using rayon to (independently) initialize some statistical models. However, this causes the results to become non-deterministic. If I switch back to being single-threaded and initialize the models in different orders the results are deterministic and identical to each other, suggesting that the problem is not due to thread-local variables. If I use `crossbeam::scope` instead of `par_iter_mut().for_each()` the non-determinism also goes away. What could be causing this? Could there be a difference in how rayon initializes the threads in its thread-pool compared to `crossbeam::scope`?

**Comment by cuviper** [comment]
If you use any `fold`, `reduce`, or the like with computations that are sensitive to associativity, as floating point operations are, then yes your results will be non-deterministic. The work-stealing in the thread pool is random, and parallel iterators are dynamically and adaptively split, so you will probably get different item groups each time.

It's hard to suggest solutions without seeing your code. If you have a slice or vector input, one possibility might be to process it with `par_chunks` of a fixed size, then collect the calculated results from each chunk and fold/reduce them serially in order.

**Comment by yongqli** [comment]
Ok, it turns out that the issue was that there was a call to `reduce()` deeply nested in a subroutine. When the top-level code was single threaded it just so happened that it didn't trigger any non-determinism, but when I parallelized the top-level code it revealed the non-determinism that was present in the sub-routine all along.

Thanks.
