### ISSUE TITLE
Processing a list in order and stop arbitrarily

### ISSUE THREAD

**Issue by Kerollmops** [rayon-rs/rayon#678]
Hi,

I am trying to find the best way to generate the expected behavior with the right rayon component.

I have a list of ordered strings, these strings will allow me to produce things, but I have a time constraint. Fortunately these strings are ordered in a way that the firsts will produce more interesting results than the lasts. So, what I would like is to process these strings in order and, once the time limit is reached, stops processing new strings.

I have tried with a simple `into_par_iter` combined with a `flat_map` but [it seems like it does not process the vector in order](https://github.com/rayon-rs/rayon/issues/551). So I thought of using [the `split` helper function](https://docs.rs/rayon/1.1.0/rayon/iter/fn.split.html) which seems to let me achieve this behavior, yielding one element from the vector at a time and once the time is reached, returning `None` which will stop threads from being fed with data.

What do you recommend to me? Do you think this could be a viable solution?

**Comment by Kerollmops** [comment]
Humm... I just found [the `ParallelBridge` trait](https://docs.rs/rayon/1.1.0/rayon/iter/trait.ParallelBridge.html), I will see if I can produce the expected behavior that I wanted (stop producing values after a given duration).

**Comment by cuviper** [comment]
Yes, I think `ParallelBridge` will be closer to what you want. Note that it pulls from the serial iterator in batches, currently 2n<sup>2</sup> items at a time (subject to change), so you may want to include your time-based cancellation in the parallel side of things as well, e.g. with [`while_some`](https://docs.rs/rayon/1.1.0/rayon/iter/trait.ParallelIterator.html#method.while_some).

**Comment by Kerollmops** [comment]
Yeah, I did not know that it pulled items by batches so I put my cancellation on the sequential side, producing great results, I tried with the cancellation on the parallel side and results were way better.

Thank you, I think you can close this issue now.

**Comment by cuviper** [comment]
Great, I'm glad it's working!
