### ISSUE TITLE
docs: Link to the ParallelIterator from the intro?

### ISSUE THREAD

**Issue by vorner** [rayon-rs/rayon#687]
When I open the https://docs.rs/rayon/1.2.0/rayon/, there's a lot of links to various parts of the documentation. However, I myself usually want to look at the methods of `ParallelIterator` at https://docs.rs/rayon/1.2.0/rayon/iter/trait.ParallelIterator.html, which is not linked from there.

As the main trait of crate, would it make sense to have it linked directly somewhere at the top, maybe instead of the `iter` submodule (which one is seldom the thing users really need to interact with directly)?

I'm not sending a PR, because I want to ask about the exact location and wording first 😇.

**Comment by cuviper** [comment]
> I'm not sending a PR, because I want to ask about the exact location and wording first innocent.

Please use your judgement for what makes sense to you as a user!

But if you want a suggestion, how about sub-bullets under "Parallel iterators make it easy ..."

- The `ParallelIterator` trait defines general methods for all parallel iterators.
- The `IndexedParallelIterator` trait adds methods for iterators that support random access.

(with both trait names appropriately linked)
