### ISSUE TITLE
Feedback: seeing 150% improvement in performance from 1.0.3 -> 1.2.0

### ISSUE THREAD

**Issue by jondot** [rayon-rs/rayon#696]
Hi all
Just feedback from a real-world workload (non-public system), upgraded from `1.0.3` to `1.2.0` and got a free 150% performance boost. Great work!

Please feel free to close :)

**Comment by cuviper** [comment]
That's great, thanks for sharing! Can you give any broad info about how you use rayon? e.g. lots of spawns, particular iterator calls, etc.
