### ISSUE TITLE
How to parallelize this with Rayon?

### ISSUE THREAD

**Issue by calebwin** [rayon-rs/rayon#699]
This is a bit of a rhetorical question but it will be quite useful for me to know. Here is my sequential code-

```rust
fn main() {
    let data = vec![0, 8, 5];
    let mut result = vec![0, 0, 0];

    for i in 0..3 {
        result[i * 3 / 3] = data[0] + data[1] + data[0 + 1 + 2];
    }
}
```

How can I parallelize this with Rayon? I want to make as few changes to the code as possible. Specifically, I would like to keep this statement `result[i * 3 / 3] = data[0] + data[1] + data[0 + 1 + 2];` preserved somewhere.

How can this be done with Rayon?

**Comment by cuviper** [comment]
The usual approach is to first change the `for` loop to an `Iterator::for_each` call, and then try to flip that to a `ParallelIterator`. So yours would start like this:

```rust
(0..3).for_each(|i| {
    result[i * 3 / 3] = data[0] + data[1] + data[0 + 1 + 2];
});
```

> Specifically, I would like to keep this statement ...

Then you've over-constrained the problem. You would try:

```rust
(0..3).into_par_iter().for_each(|i| {
    result[i * 3 / 3] = data[0] + data[1] + data[0 + 1 + 2];
});
```

but here you would be stuck, because that closure is `FnMut` for mutating its captured `result`. (Sharing `data` is fine.) Rayon can't call this from different threads, because it requires exclusive `&mut` access to the closure.

The closest thing to unchanged here would be to wrap that in a `Mutex`, like:

```rust
let result = Mutex::new(result);
(0..3).into_par_iter().for_each(|i| { // captures only `&result` and `&data`, so it's a `Fn`
    let value = data[0] + data[1] + data[0 + 1 + 2]; // computed outside the lock, in parallel
    let result = result.lock().unwrap(); // this may be a sequential bottleneck
    result[i * 3 / 3] = value;
});
```

I don't know the purpose of your `i * 3 / 3` index example, but in general the better solution is to restructure this into a parallel iterator on the mutable result, like:

```rust
result.par_iter_mut().for_each(|r| {
    *r = data[0] + data[1] + data[0 + 1 + 2];
});
```

Or just collect a brand new result from the iterator:

```
let result: Vec<_> = (0..3).into_par_iter().map(|i| {
    data[0] + data[1] + data[0 + 1 + 2]
})
.collect();

**Comment by calebwin** [comment]
This is really useful! Thank you for the detailed response.

My use-case is a little complicated. I'm basically building a compiler and trying to see if I can guarantee no data races with Rust + Rayon instead of writing my own checker. For simple mapping operations, this is trivial. But I'm trying to see if by using Rust + Rayon, I can assert loops over general ranges of things (like `0..10`) with loop bodies that involve mutable and immutable indexing of arrays with arbitrary index expressions (like `data[1 + computed_index + i]`).

**Comment by cuviper** [comment]
Most mutation is going to require some care to make it parallelizable, unless it's something like an `iter_mut()` that you can turn into `par_iter_mut()`.

Rayon is just a library, not integrated in the compiler, so we don't actually have any way to see what your loop bodies are doing. We just require `Fn + Sync` at a high level to allow sharing, but if you're mutating captured data you'll have `FnMut`.

**Comment by calebwin** [comment]
> Most mutation is going to require some care to make it parallelizable, unless it's something like an iter_mut() that you can turn into par_iter_mut().

So to be clear, I can't just do a `let result = Mutex::new(result);` outside of the loop for each thing I want to mutate and do a `let result = result.lock().unwrap(); result[i * 3 / 3] = value;` for each mutation? or something close to that?

> Rayon is just a library, not integrated in the compiler, so we don't actually have any way to see what your loop bodies are doing.

I understand. The compiler is embedded in a procedural macro that can generate dead code that uses Rayon. I was hoping that Rust's checker can maybe somehow look a the code and guarantee no data races by looking at the code.

**Comment by cuviper** [comment]
> So to be clear, I can't just do a `let result = Mutex::new(result);` outside of the loop for each thing I want to mutate and do a `let result = result.lock().unwrap(); result[i * 3 / 3] = value;` for each mutation? or something close to that?

You can do that -- just remember that you won't get any parallelism from the `Mutex`-locked region. If you're locking multiple things, be careful about the order of nested locks too, or you can deadlock. You should probably also avoid nesting further rayon work while in a locked section, #592.

> I was hoping that Rust's checker can maybe somehow look a the code and guarantee no data races by looking at the code.

You do get this benefit through the auto-implementations of `Send` and `Sync` traits, as well as the analysis of closure captures that makes them `Fn` (shareable) or `FnMut` (exclusive).

**Comment by calebwin** [comment]
Thank you for your help.

>>So to be clear, I can't just do a let result = Mutex::new(result); outside of the loop for each thing I want to mutate and do a let result = result.lock().unwrap(); result[i * 3 / 3] = value; for each mutation? or something close to that?
> 
> You can do that -- just remember that you won't get any parallelism from the Mutex-locked region. If you're locking multiple things, be careful about the order of nested locks too, or you can deadlock. You should probably also avoid nesting further rayon work while in a locked section, #592.

But by just wrapping all things I want to mutate with a `Mutex`, does that assert that 2 threads won't mutate the same index of that `Mutex`-wrapped data thing. That's really what I'm trying to ask.

**Comment by cuviper** [comment]
A `Mutex` will ensure that its value won't be written from multiple places _at the same time_, as they must have it locked to access the value. If you wrap the entire collection in one `Mutex`, then any writer will have to wait for a lock on the whole collection to access the index they're interested.

You could also use fine-grained locks, like `Vec<Mutex<T>>`, then each index can be locked and accessed independently. However, if there are a lot of items, this will add a lot of memory overhead in creating so many mutexes.

None of this ensures that two threads won't mutate the same index at all, only that they can't do so simultaneously.

**Comment by calebwin** [comment]
OK. Then I'm guessing I can't use this for what I want. Basically, I want to be able to make a Rust-for-loop-to-OpenCL and Rust-for-loop-to-Rayon code transformation that asserts thread safety. But since OpenCL does a mix of data-parallel and shared state model. So, if I have code like this.
```rust
for i in 0..10 {
    data[i] = 0.0;
    data[i+1] = 0.0;
}
```
I want to turn it into this OpenCL.
```c
data[get_global_id(0)] = 0.0;
data[get_global_id(0) + 1] = 0.0;
```
This isn't thread-safe, right? So I want to transform the Rust into Rust+Rayon that will be failed at compile-time by the Rust compiler. But I guess mutexes just aren't going to give me that.

**Comment by cuviper** [comment]
It is failed coarsely at compile time by the fact that rustc won't let you share mutable access to `data` at all. But the compiler doesn't try to prove that specific indexes will be unique or not.

**Comment by calebwin** [comment]
Yeah. That makes sense.

**Comment by jhpratt** [comment]
Note that while a `Mutex` will work, an async implementation of it is not as easy to do.
