### ISSUE TITLE
Child process cannot spawn thread from pool which was created by the parent process

### ISSUE THREAD

**Issue by bachue** [rayon-rs/rayon#708]
This code will never end because the scope thread from child process cannot run.

I think rayon should recreate all threads after the child process was created. Or at lease, provide an interface to let us do that.

```rust
use nix::{
    sys::wait::waitpid,
    unistd::{fork, ForkResult},
};
use rayon::ThreadPoolBuilder;

fn main() {
    let thread_pool = ThreadPoolBuilder::new().num_threads(5).build().unwrap();
    match fork() {
        Ok(ForkResult::Parent { child, .. }) => {
            println!(
                "Continuing execution in parent process, new child has pid: {}",
                child
            );
            thread_pool.scope(|r| {
                r.spawn(|_| {
                    println!("Job from parent process");
                });
            });

            waitpid(Some(child), None).unwrap();
        }
        Ok(ForkResult::Child) => {
            println!("I'm a new child process");
            thread_pool.scope(|r| {
                r.spawn(|_| {
                    println!("Job from child process");
                });
            });
        }
        Err(_) => println!("Fork failed"),
    }
}
```

**Comment by cuviper** [comment]
I don't think we can support Rayon after `fork` at all, especially after the threadpool has started, because POSIX is quite limited in what you can do at that point:

http://man7.org/linux/man-pages/man3/fork.3p.html
>         *  A process shall be created with a single thread. If a multi-
>            threaded process calls fork(), the new process shall contain a
>            replica of the calling thread and its entire address space,
>            possibly including the states of mutexes and other resources.
>            Consequently, to avoid errors, the child process may only execute
>            async-signal-safe operations until such time as one of the exec
>            functions is called. Fork handlers may be established by means of
>            the pthread_atfork() function in order to maintain application
>            invariants across fork() calls.

Very few pthread functions are on that safe list, so we have no way to start a new pool.
http://man7.org/linux/man-pages/man7/signal-safety.7.html

**Comment by joshtriplett** [comment]
Agreed; you really can't safely do much after forking a threaed process except call exec.
