### ISSUE TITLE
For performance optimization of algorithms we need a simple way to serialize code with rayon primitives

### ISSUE THREAD

**Issue by przygienda** [rayon-rs/rayon#722]
Once rayon is in the code perf & flamegraph seem to show just the scheuling in/out of workers. It would be ideal to have something where rayon has a feature along the lines of "serial-only" where all the parellization is switched off and the algorithms under rayon run like normal serial code so perfomrance of pieces can be easily seen ...

**Comment by cuviper** [comment]
Please see #591.
