### ISSUE TITLE
The code snipped cause runtime error.

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [rayon-rs/rayon#727]
I received error on running this code using `cargo run --release`. On `cargo run` It works good.

```rust
fn main() {
    rayon::scope(|scope|{
        for _ in 0..32{
            scope.spawn(|_|loop{
            });
        };
    });
}
```

Error:
```
   Compiling rayon_test v0.1.0 (E:\Programs\Rust\rayon_test)
    Finished release [optimized] target(s) in 0.55s
     Running `target\release\rayon_test.exe`
error: process didn't exit successfully: `target\release\rayon_test.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

The operating system: Windows 10 x64
Rust: rustc 1.41.1 (f3e1a954d 2020-02-24)
Rayon: 1.3.0
CPU: AMD Ryzen 2700X

**Comment by cuviper** [comment]
Yes, I expect this is https://github.com/rust-lang/rust/issues/28728.

LLVM treats an infinite loop without side effects as undefined behavior and decides this is unreachable. The Rust compiler sets `TrapUnreachable`, which on x86 generates a `ud2` instruction, triggering termination.
