### ISSUE TITLE
.take() cannot be used after .filter()

### ISSUE THREAD

**Issue by is8ac** [rayon-rs/rayon#745]
## code 
```
use rayon::prelude::*;

fn main() {
    let list: Vec<usize> = (0..10000).collect();

    let sum: usize = list.par_iter().filter(|&x| x % 3 == 0).take(30).sum();

    let sum: usize = list.iter().filter(|&x| x % 3 == 0).take(30).sum();
    let sum: usize = list.par_iter().filter(|&x| x % 3 == 0).sum();
    let sum: usize = list.par_iter().take(30).sum();
}
```
Comment out the first `.par_iter()` line and it compiles.

## error
```
error[E0599]: no method named `take` found for struct `rayon::iter::filter::Filter<rayon::slice::Iter<'_, usize>, [closure@src/bin/rayon_filter_take_example.rs:6:45: 6:60]>` in the current scope
  --> src/bin/rayon_filter_take_example.rs:6:62
   |
6  |     let sum: usize = list.par_iter().filter(|&x| x % 3 == 0).take(30).sum();
   |                                                              ^^^^ method not found in `rayon::iter::filter::Filter<rayon::slice::Iter<'_, usize>, [closure@src/bin/rayon_filter_take_example.rs:6:45: 6:60]>`
   | 
  ::: /home/isaac/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.0/src/iter/filter.rs:13:1
   |
13 | pub struct Filter<I: ParallelIterator, P> {
   | ----------------------------------------- doesn't satisfy `_: std::iter::Iterator`
   |
   = note: the method `take` exists but the following trait bounds were not satisfied:
           `rayon::iter::filter::Filter<rayon::slice::Iter<'_, usize>, [closure@src/bin/rayon_filter_take_example.rs:6:45: 6:60]>: std::iter::Iterator`
           which is required by `&mut rayon::iter::filter::Filter<rayon::slice::Iter<'_, usize>, [closure@src/bin/rayon_filter_take_example.rs:6:45: 6:60]>: std::iter::Iterator`

error: aborting due to previous error
```

Is this intentionally forbidden? Perhaps `.filter()` followed by `.take()` would be non deterministic, or otherwise could not be implemented correctly?

If this capability could be added, I'd appreciate it, otherwise explicit documentation of the limitation  would be helpful.

**Comment by cuviper** [comment]
> Perhaps `.filter()` followed by `.take()` would be non deterministic, or otherwise could not be implemented correctly?

Right -- if we're process items in parallel, out of order, how are we supposed to know which `n` items to take? It would essentially be serialized on the ordered result of filtering. This is why rayon's `take` is a method of `IndexedParallelIterator`, requiring that we're able to access any of the correct `n` items in parallel.

If you have useful parallel work to do after the take, you could filter it serially and then bridge:

```rust
list.iter().filter(...).take(n).par_bridge().for_each(...);
```

---

This does give me an idea: we could add something like `take_any` (and `skip_any`) which atomically tracks the count in parallel and takes (or skips) the "first" `n` items in the arbitrary order of parallel visitation. This would definitely be non-deterministic, but maybe it could be useful for something like fuzzy search results? e.g. "Give me any 10 items that match this predicate."

**Comment by is8ac** [comment]
Thank you for the conformation.

I ended up refactoring to work around this.

Unless you want to add some explanation to the documentation, feel free to close this issue.

**Comment by cuviper** [comment]
I would welcome additions to the documentation, though this would probably belong in a more general scope, discussing the distinction made by `IndexedParallelIterator`. If anyone would like to work on that, please feel free, but I don't think we need this particular issue to stay open.
