### ISSUE TITLE
Doc wording: mixed verb moods

### ISSUE THREAD

**Issue by adrian5** [rayon-rs/rayon#748]
While reading the documentation, I noticed that doc comments (`///`) use e.g.

> Create**s** an iterator which clones all of its elements.\
> Create a new `Cloned` iterator.

And more apparently:

> Create a "fork-join" scope `s` with FIFO order, and invoke**s** the closure with a reference to `s`.

I'm aware that tests and regular inline comments can differ in that regard. For doc comments though, is there a preference? I can create a PR that brings them in line.

**Comment by cuviper** [comment]
Consistency would be good, *especially* within the same sentence! :sweat_smile: 

I think the convention in `std` is to use the indicative mood, like "[This method] creates ...". Even then, I quickly found inconsistencies at a glance of my open tabs, for example:

- `ManuallyDrop::new`: "Wrap a value"
- `ManuallyDrop::into_inner`: "Extracts a value"

**Comment by nikomatsakis** [comment]
I think I prefer "Creates..." to "Create....", but I don't really have a strong opinion about this.

**Comment by adrian5** [comment]
I too prefer it in the sense that it's something the _program_ does; not every function is called explicitly through programmers' intent. I'll file a small PR that brings them in line and you can edit that if I go overboard :wink:
