### ISSUE TITLE
Can I apply par_iter for iterator without collect?

### ISSUE THREAD

**Issue by sergeyt** [rayon-rs/rayon#764]
instead of

```rust
let v: Vec<f64> = data.iter_f64().collect();
let result: f64 = v.par_iter().sum();
result.into()
```

i'd like to write

```rust
let result data.iter_f64().par_iter().sum();
result.into()
```

i've got error:

```
pub enum ValueIterF64<'a> {
    | -------------------------
    | |
    | method `par_iter` not found for this
    | doesn't satisfy `_: rayon::iter::IntoParallelRefIterator`
    |
    = note: the method `par_iter` exists but the following trait bounds were not satisfied:
            `&value::ValueIterF64<'_>: rayon::iter::IntoParallelIterator`
            which is required by `value::ValueIterF64<'_>: rayon::iter::IntoParallelRefIterator`
```

**Comment by cuviper** [comment]
You can use [`par_bridge`](https://docs.rs/rayon/1.3.0/rayon/iter/trait.ParallelBridge.html#tymethod.par_bridge) as long as your iterator implements `Send`. However, in your example only the `sum()` will actually run in parallel, which may not be worth the overhead.

**Comment by cuviper** [comment]
Also, beware that floating point addition is not associative, so you won't get completely deterministic results from this in parallel.

**Comment by sergeyt** [comment]
@cuviper got it, thanks
