### ISSUE TITLE
crossbeam-queue 0.2.2 yanked

### ISSUE THREAD

**Issue by r3dlight** [rayon-rs/rayon#767]
Rayon-core 1.7.0 depends on crossbeam-queue 0.2.2 but package has been yanked! See: 
https://crates.io/crates/crossbeam-queue/0.2.2

**Comment by cuviper** [comment]
Rayon only requires 0.2 -- as a user you can upgrade or downgrade to a different 0.2.x release if needed.

**Comment by r3dlight** [comment]
Ok thx, for information, I had this warning using cargo audit and rayon 1.3.0.
