### ISSUE TITLE
par_iter for Range*<char>

### ISSUE THREAD

**Issue by CAD97** [rayon-rs/rayon#770]
With https://github.com/rust-lang/rust/pull/72413, ranges of `char` are now iterable (in 1.45, releasing 2020-07-16). Rayon should support iterating them in parallel just like normal continuous integer ranges.

[I've done experimentation previously](https://github.com/CAD97/mileage/blob/master/src/range/par_iter.rs), which suggested that `chain(chars before surrogate range, chars after surrogate range)` is the optimal `ParallelIterator` for `Range*<char>`.

I've very little experience with implementing parallel iterators, however, so that could be untrue.

**Comment by cuviper** [comment]
Sure, we can add that.

A chain sounds fine, but I wouldn't necessarily encode that in the iterator fields. It could just use `rayon::range::Iter<char>`, and then in its specific `fn drive` it can forward to something like `(start as u32..end as u32).into_par_iter().map(/*to char*/).drive(..)`, or chained if needed to skip surrogates. Point is, that implement choice can be dynamic.
