### ISSUE TITLE
Abnormal “memory allocation of  bytes failed”

### ISSUE THREAD

**Issue by linweijun** [rayon-rs/rayon#775]
When I use this library or the[ official tutorial ](https://doc.rust-lang.org/1.19.0/book/second-edition/ch20-04-storing-threads.html)for thread pool, I get an error with the error alert "memory allocation of _ bytes failed Aborted". I'm confused? Why is that? I test it on a 1-core 1GB RAM or 2-core 4G machine with the thread pool size set to 500 or higher, and it also has Such situation. The code is below and I need help to see how I should optimize it. The test file contains 1.7 million lines of string.

170w.txt 

```
0
112
11111
1asdq
.......

````
```
use std::fs::File;
use std::io::*;
use std::{thread, time};
use rayon;
use rand::Rng;


fn main() {
    println!("Hello, world!");
        let pool = rayon::ThreadPoolBuilder::new().num_threads(22).build().unwrap();
        let s_dict = init_target("170w.txt");

    for _ in vec![1,2,3,4,5] {
        for sa in s_dict.clone() {
            pool.spawn (move ||{
                //  do some.........
                let mut rng = rand::thread_rng();
                let y = rng.gen_range(0, 10);

                thread::sleep(time::Duration::from_millis(y));
                println!("read {:?} sleep {}", sa, y);

            })
        }
    }
    
}


pub fn init_target(filename: &str) -> Vec<String> {
    let mut target = Vec::new();

    let f = File::open(filename).unwrap();

    let reader = BufReader::new(f);

    for item in reader.lines() {
        match item {
            Ok(item) => {
                target.push(item);
            }
            Err(_) => {
            }
        }
    }

    target
}
```

**Comment by cuviper** [comment]
Why are you creating so many threads? With a thread pool, the goal is usually to match the number of logical CPUs in your system. Otherwise, your system will be [oversubscribed](https://en.wikipedia.org/wiki/Resource_contention) with competing threads, and a fair OS scheduler will have to frequently switch the active thread on each CPU, which is bad for performance.

The [default stack size](https://doc.rust-lang.org/std/thread/index.html#stack-size) for Rust threads is 2MiB. If you create a thread pool with 500 threads, that's 1000MB of memory _just_ for the thread stacks, on top of any memory for your actual data.

**Comment by linweijun** [comment]
> Why are you creating so many threads? With a thread pool, the goal is usually to match the number of logical CPUs in your system. Otherwise, your system will be [oversubscribed](https://en.wikipedia.org/wiki/Resource_contention) with competing threads, and a fair OS scheduler will have to frequently switch the active thread on each CPU, which is bad for performance.
> 
> The [default stack size](https://doc.rust-lang.org/std/thread/index.html#stack-size) for Rust threads is 2MiB. If you create a thread pool with 500 threads, that's 1000MB of memory _just_ for the thread stacks, on top of any memory for your actual data.

I wanted to get the file processing done as quickly as possible, so I set up the thread pool to be large, and on some machines the queries are very, very fast indeed! Get the job done, but some machines don't work. Do you have any good suggestions? Thank you.

**Comment by cuviper** [comment]
If your tasks are primarily CPU-bound, rayon may be well suited, but there wouldn't be any benefit to using more threads than CPUs. If your tasks are frequently waiting on I/O, then using a lot of threads can somewhat hide that, but you might be better off exploring an asynchronous runtime like `tokio` or `async-std`.

**Comment by linweijun** [comment]
> If your tasks are primarily CPU-bound, rayon may be well suited, but there wouldn't be any benefit to using more threads than CPUs. If your tasks are frequently waiting on I/O, then using a lot of threads can somewhat hide that, but you might be better off exploring an asynchronous runtime like `tokio` or `async-std`.

Ok, thank you
