### ISSUE TITLE
#746 new thread scheduler is unreleased

### ISSUE THREAD

**Issue by sakridge** [rayon-rs/rayon#784]
The new thread scheduler dramatically helps CPU usage for our use case. Can we get a release with it included? Thanks!

**Comment by sakridge** [comment]
cc @cuviper

**Comment by cuviper** [comment]
Hi -- yes, we should actually pull the trigger and release this. I'm hoping to sync with @nikomatsakis on some of the other outstanding PRs, but I might just go ahead with the simpler ones and then publish.

**Comment by cuviper** [comment]
It's now published!
- `rayon-core 1.8.0`
- `rayon 1.4.0`
