### ISSUE TITLE
Work with itertools

### ISSUE THREAD

**Issue by GalAster** [rayon-rs/rayon#813]
I want to speed up some operations in itertools like `cartesian_product`, `permutations` , `multi_cartesian_product`, but it seems that certain conditions are not met.

```toml
[dependencies]
itertools = "0.9"
rayon = "1.5"
```

```rust
use itertools::Itertools;
use rayon::iter::{IntoParallelIterator};

#[test]
fn main() {
    let mut sum = 0;
    for i in (0..3).map(|_| -1..1).multi_cartesian_product().into_par_iter() {
        sum += i.iter().sum1::<i32>().unwrap()
    }
    println!("{}", sum)
}
```

```yaml
   |
15 | / pub struct MultiProduct<I>(Vec<MultiProductIter<I>>)
16 | |     where I: Iterator + Clone,
17 | |           I::Item: Clone;
   | |                         -
   | |                         |
   | |_________________________doesn't satisfy `_: rayon::iter::IntoParallelIterator`
   |                           doesn't satisfy `_: rayon::iter::ParallelIterator`
   |
   = note: the method `into_par_iter` exists but the following trait bounds were not satisfied:
           `itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::ParallelIterator`
           which is required by `itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::IntoParallelIterator`
           `&itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::ParallelIterator`
           which is required by `&itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::IntoParallelIterator`
           `&mut itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::ParallelIterator`
           which is required by `&mut itertools::MultiProduct<std::ops::Range<{integer}>>: rayon::iter::IntoParallelIterator`
```

I seem to need to implement `IntoParallelIterator` manually

Because of the orphan rule, am I unable to patch when I use both at the same time?

**Comment by cuviper** [comment]
> ```rust
>     for i in (0..3).map(|_| -1..1).multi_cartesian_product().into_par_iter() {
> ```

There are two problems here -- `MultiProduct` doesn't implement `IntoParallelIterator`, as you saw, but also `for` loops are hard-coded in the language to use the `Iterator` trait.

There's no direct way for you to parallelize `MultiProduct` from `itertools`. We could possibly implement a custom `rayon` version of the same concept, but I'm not sure how well that would work. The other option is to use `par_bridge()` as the generic wrapper from `Iterator` to `ParallelIterator`, but that does come with synchronization overhead. Bridging isn't going to be worth it unless you have a significant amount of parallel work to do on each item out of the sequential iterator, but your example of summing is probably not enough work.

To get away from the `for` loop, you'll need to convert to a functional style like:

```rust
    iter.par_bridge().for_each(|i| {
        // ...
    });
```

Parallel `for_each` requires a shared `Fn` closure though, so it can't be mutating captured state like your `sum` variable. You could change that to an atomic type, or there's also a parallel method for summation:

```rust
    let sum = iter.par_bridge().map(|i| /* internal summation */).sum();
}

**Comment by GalAster** [comment]
Thanks for your help, `par_bridge` is indeed the solution I am looking for.
