### ISSUE TITLE
assertion failed: injected && !worker_thread.is_null() when used as cdylib

### ISSUE THREAD

**Issue by vtavernier** [rayon-rs/rayon#816]
I have a project using rayon (through the `rayon` feature of `ndarray`), and have encountered an odd assertion failure.

In this project, a core crate (let's call it `crate_a`) defines some primitives for computation, including the creation of a `rayon::ThreadPool`. A second crate (let's call it `crate_b`) can do some computations using the primitives from `crate_a`. Thus, it has a dependency on `crate_a`.

This works perfectly from Rust. However, these two crates also expose their functionality through a C API when built as a cdylib. The C program has both `libcrate_a.so` and `libcrate_b.so` as dependencies, as it uses functionality from both:
```c
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <stdbool.h>

struct ThreadPool;
typedef struct ThreadPool ThreadPool;

extern ThreadPool* new_rayon_pool();                  // from crate_a
extern void do_something_with_pool(ThreadPool *pool); // from_crate_b

int main(int argc, char *argv[]) {
	ThreadPool *pool = new_rayon_pool(); // works
	do_something_with_pool(pool);        // assertion fails
	return 0;
}
```

When calling methods from `crate_b` that use the rayon pool created by `crate_a`, this results in the following panic:
```
thread '<unnamed>' panicked at 'assertion failed: injected && !worker_thread.is_null()', /home/vincent/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:468:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

I have reproduced this in a minimal working example in this repository: https://github.com/vtavernier/rayon-bug-cdylib. You can compile the C example with `make`, and:
* Running `./example` should fail with the above error
* Running `cargo test` should succeed

I am aware this is a non-standard situation compared to the expected use of a Rust crate, but I am still opening this issue in the hopes someone knows what linker dark magic may be needed to fix this.

**Comment by cuviper** [comment]
I believe `rustc` hides all Rust-ABI symbols as internal linkage when compiling a `cdylib`, which would mean your two libraries won't be able to share any globals or thread locals. This would affect Rayon in its global `ThreadPool` and the thread local worker state, and it seems the latter explains your assertion failure.

For "linker dark magic", it might work better to compile as `staticlib` instead, and try to control symbol visibility when linking the shared object yourself. You may want to keep _all_ Rust data symbols visible for this purpose.

**Comment by vtavernier** [comment]
It is indeed the problem. If I compile the 2 crates as `staticlib` I can link them with the C code to create a working executable.

However, if a cdylib is required (for loading Rust code into some host program instead of linking everything together), since https://github.com/rust-lang/rfcs/issues/2771 is still open the only option seems to create a specific C API cdylib crate with all the required dependencies. I failed to find previous work on linking multiple `cdylib` having shared Rust dependencies, so for now this seems to be the only way, even if not the most flexible.

**Comment by nikomatsakis** [comment]
It seems like this is resolved, or at least can't be fixed in rayon, so I'm going to close. Thanks for filing!
