### ISSUE TITLE
If not the CPU is the bottlenck, then what?

### ISSUE THREAD

**Issue by errrken** [rayon-rs/rayon#818]
Hi,

I have a genetic algorithm that uses rayon and par_iter to calculate each individual per generation. When I check how much time is spent in the par_iter method - it's about 92% of total runtime. But when I go from using iter() to par_iter() I only see a ~3x speedup which according to Amdahls law should result in a higher speedup? 

That makes me believe the CPU aint the bottleneck? When using par_iter() when 2 cores are enabled, then each core runs at 100% of the runtime. However, when utilizing all of my 8 cores, they are averaging 90% of each core. Is this the reason I don't see the expected speedup? If so, then what may be the bottleneck?

Thanks

**Comment by JackThomson2** [comment]
Hey, I by no means a rayon expert, but played with it a fair amount. As far as I can tell the higher the parallelism the greater the overhead in the allocation of work. One thing to try may be to use the ```chunks()``` extension [chunks](https://docs.rs/rayon/1.5.0/rayon/iter/trait.IndexedParallelIterator.html#method.chunks) it seemed to provide a speedup for me with a higher core count.

**Comment by cuviper** [comment]
You'll probably need to profile your application to see where it's spending time, and try different event counters as well. My wild guess would be that you're running into limited memory bandwidth, which may show up in events like cache misses.

**Comment by errrken** [comment]
Thanks a lot for your answers. I tried to clone one of the parameters used instead of accessing it by reference, which I guess(?) reduced the synchronization work required. Anyhow, now it seems like it scales well, reaching a ~11 speedup on 64 threaded CPU which seems inline with Amdahls law.
