### ISSUE TITLE
Limit number of sublists created with fold

### ISSUE THREAD

**Issue by SuperFluffy** [rayon-rs/rayon#840]
I am folding over a large amount of input files. My fold looks something like this:

```rust
input_files
    .par_iter()
    .fold(|| OutputFiles::new(), |output_files, input_file| {
        some_work(&input_file, &output_files);
        output_files
    })
    .reduce( // recombines all output files into one )
```

The idea is that each worker has a set of output files (randomly generated temp files like `<random>_foo`, `<random>_bar`), and each worker appends data extracted from `input_file` according to some rule, placing it in `*_foo` or `*_bar` and so on.

Now my problem is that this method results in too many open file descriptors. Reading `ParallelIterator::fold`, it says:

> The parallel fold works similarly except that it first breaks up your list into sublists, and hence instead of yielding up a single sum at the end, it yields up multiple sums. The number of results is nondeterministic, as is the point where the breaks occur.

Is there a way to limit this number of sublists in any way so that I don't end up with a too large number of intermediate output files?

**Comment by SuperFluffy** [comment]
I have fixed (or circumvented) the problem by using a `Arc<Pool<OutputFiles>>` object pool (from the object pool crate)  and `ParallelIterator::try_for_each_init` instead.

**Comment by wagnerf42** [comment]
i guess the blocking schemes which we are working on right now would actually solve your issue. so it might be just a matter of time.
