### ISSUE TITLE
UB in Collect:: reserve_get_tail_slice

### ISSUE THREAD

**Issue by erickt** [rayon-rs/rayon#851]
It appears that [Collect::reserve_get_tail_slice](https://github.com/rayon-rs/rayon/blob/master/src/iter/collect/mod.rs#L139) might have undefined behavior. The code is reserving uninitialized space, then creating a mutable reference to it. This us UB according to this [documentation](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html).

**Comment by cuviper** [comment]
I thought the validity of uninitialized data behind references hasn't been decided yet ([UCG#77](https://github.com/rust-lang/unsafe-code-guidelines/issues/77)), but I guess we could probably use `&mut [MaybeUninit<T>]` here.
