### ISSUE TITLE
iter_mut fails to error that variable doesn't live long enough or mutate

### ISSUE THREAD

**Issue by evergreen-trading-systems** [rayon-rs/rayon#866]
I am mutating nested vectors in a parallel for_each.

```
use rayon::prelude::*;

    let mut a = vec![vec![1, 2, 3, 4], vec![2, 3, 4, 5, 6]];
    let aiter :rayon::slice::IterMut<Vec<i64>> = a.par_iter_mut();

    // This should complain `c` does not live long enough or I should see 0 at index 0. Bug
    aiter.enumerate().for_each(|(u, mut x)|{
        let mut c = x.clone();
        x = &mut c;
        x[0] = 0;
    });

    println!("{:?}",a); //[[1, 2, 3, 4], [2, 3, 4, 5, 6]]
```

**Comment by cuviper** [comment]
Your `mut x` starts out referencing `a`, and then you change it to reference the local `c` instead. In doing this, you are mutating the reference itself, independent of `a`. Your `0` assignment only modifies the local `c`, which is then dropped as the closure returns. Remember that the `x` parameter is also just a local, so changing it only has local effect.

You don't need `rayon` for this either -- the same happens with the standard `iter_mut`. It's not a bug.

**Comment by evergreen-trading-systems** [comment]
Cool, makes sense. I thought what I thought because if you remove `enumerate`, it complains `c` doesn't live long enough. Don't know why.

**Comment by evergreen-trading-systems** [comment]
If you know why, please let us know. Meantime, I'll close this.

**Comment by cuviper** [comment]
Oh interesting -- there must be something funny happening to the lifetime when the pattern unpacks the tuple. If you keep the enumerate and take the parameter as `|mut x|`, accessing the reference via `x.1` in each use, that also complains.

Playgrounds:

- [works with enumerate and an unpacked pattern](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b009222c799cdba87e12e8cd52d01b67)
- [fails with enumerate and tuple indexing](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6df2a3e669bd921869f8387b994403a5)
- [fails without enumerate](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d618816d7097363a5c9bfd06ceff434a)

@nikomatsakis can you explain?

**Comment by cuviper** [comment]
I _think_ in the pattern case, `|(_, mut x)|`, that `x` is reborrowed from the outer `IterMut` reference, letting it take on a shorter lifetime that is compatible with `c`. The other cases use the `IterMut` reference as-is, with the outer lifetime.

**Comment by cuviper** [comment]
You can reborrow it yourself by shadow-binding: `let mut x = x;`
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f117931efe8127d2b6f601920c7efa83

**Comment by nikomatsakis** [comment]
Hmm. I'm a bit surprised that the original compiles to be honest -- I don't think it's *unsafe*, but I would indeed expect the type system not to be smart enough to fully understand it.

**Comment by nikomatsakis** [comment]
Oh, I know why.

**Comment by nikomatsakis** [comment]
I think this has to do with the details of how the MIR desugaring works. I'm not sure it's *intentional*, but it's interesting... when you have `(u, mut x)` as the parameter pattern, the closure is effectively converted into this:

```rust
|tmp| {
     let (u, mut x) = tmp;
}
```

and so `x` is a local variable inside the closure. Therefore, it's lifetime is independent from `tmp` and it can be given a lifetime that includes the lifetime of `c`. The *actual argument* (`tmp`) has to have a lifetime that is "external" from the closure body (something the caller could reference). 

If you don't have a pattern (or, rather, you have a trivial pattern like `x`) you get a hard error either way.

**Comment by nikomatsakis** [comment]
This feels unfortunate, but I'm trying to decide what fix I would want to apply. :)

**Comment by cuviper** [comment]
To be clear, that would be a compiler fix, not anything particular to rayon. Shall we move this to rust-lang/rust?

@evergreen-trading-systems kudos on finding an interesting corner case in the language!

**Comment by evergreen-trading-systems** [comment]
Thanks, @cuviper and @nikomatsakis for the explanation. I leave the rest to you.
