### ISSUE TITLE
Data race in crossbeam-deque

### ISSUE THREAD

**Issue by zekun000** [rayon-rs/rayon#879]
See https://rustsec.org/advisories/RUSTSEC-2021-0093

Not sure how much rayon is affected, can we upgrade the dependency and backport to existing release?

**Comment by zekun000** [comment]
closing since upgrading crossbeam-deque to 0.8.1 doesn't require anything from rayon side.

**Comment by cuviper** [comment]
That's right, you can update it with semver compatibility, but #876 is also updating the explicit dependency.
