### ISSUE TITLE
Pattern for nested loops that avoids double cloning?

### ISSUE THREAD

**Issue by multimeric** [rayon-rs/rayon#881]
This started as a StackOverflow question: https://stackoverflow.com/q/68961129/2148718. Basically I have this pattern where I have an outer loop that runs serially on the main thread, and an inner loop that runs in parallel. After each inner loop has finished I check the results and possibly terminate early, so I can't just cartesian product these two iterators into one parallel iterator. I would like to be able to do this, however I obviously can't as each `for_each_with` will take ownership of the **`sender`**:
```rust
    let (sender, receiver) = channel();
    (0..5).for_each(|i|{
        (0..5).into_par_iter().for_each_with(sender, |sender, j|{
            sender.send(i + j).unwrap();   
        });
        // Use receiver and terminate early if necessary
    });
```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3d27dfdaf41f1cd4bcd54a5648374424)).

Unfortunately the only way this can work is by cloning `sender` each outer loop iteration, which is actually unnecessary because it's going to be cloned anyway for each thread:
```rust
    (0..5).for_each(|i|{
        (0..5).into_par_iter().for_each_with(sender.clone(), |sender, j|{
            sender.send(i + j).unwrap();   
        });
    });
```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cac9584fb1c7472399cbac36f0f481dd))
So I end up with `n x m + m` clones which is a bit wasteful. The other option I tried is cloning a reference to sender, but for some reason I don't fully understand, this doesn't work:
```rust
    (0..5).for_each(|i|{
        (0..5).into_par_iter().for_each_with(&sender, |sender, j|{
            sender.send(i + j).unwrap();   
        });
    });
```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=672cca8549c65d2b17e2e8236bbe6261))

Is there a idomatic `rayon` way to solve this without the wasteful cloning?

**Comment by cuviper** [comment]
I don't have a great rayon solution for this. I think you'd want real thread-local variables to let it survive across serial iteration, and scoped as well. If this is at a high enough level where you're comfortable controlling the threadpool itself, you could possibly use a [`spawn_handler`](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPoolBuilder.html#method.spawn_handler) with `scoped_tls`, like this test code:
https://github.com/rayon-rs/rayon/blob/master/rayon-core/tests/scoped_threadpool.rs

Or much simpler, if you switch to `crossbeam-channel`, its [`Sender`](https://docs.rs/crossbeam-channel/0.5.1/crossbeam_channel/struct.Sender.html) is `Sync` and only requires `&self` for sending. That means you can just borrow the one instance across all loops without any cloning at all! ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8645565e54946bd65d1d521795a0930d))

**Comment by multimeric** [comment]
Thanks for this answer. The crossbeam channel was suggested elsewhere and seems like a neat solution to this. But it's also good to know there's no easy rayon way to solve this.
