### ISSUE TITLE
ARM Neon support?

### ISSUE THREAD

**Issue by fzyzcjy** [rayon-rs/rayon#889]
Hi thanks for the lib! I wonder this library supports ARM neon SIMD instructions?

**Comment by cuviper** [comment]
Rayon doesn't do any explicit instruction-level parallelism, but it's still possible that the LLVM vectorizer will optimize inner loops. We try to push things down to `Iterator::fold` and the like after splitting it up for thread parallelism.

**Comment by fzyzcjy** [comment]
Thanks!
