### ISSUE TITLE
Bitdefender flagged rayon

### ISSUE THREAD

**Issue by SankaD** [rayon-rs/rayon#899]
![image](https://user-images.githubusercontent.com/2997480/141782877-b4cc74d6-daf5-4325-98c3-3e97eec72780.png)

Not sure whether this is an issue with  rayon or Bitdefender. Just posting here for anyone interested.

**Comment by cuviper** [comment]
It's almost certainly a false positive -- `rayon-core/build.rs` is trivial, just a single `println!`.
