### ISSUE TITLE
Pointer being realloc'd was not allocated

### ISSUE THREAD

**Issue by djc** [rayon-rs/rayon#901]
I'm not sure that this is an issue with rayon, but at this point it does seem like the most likely candidate, so I'd like to get another set of eyes on this.

I have a CLI app which is crashing when run in release mode on macOS 12.0.1, compiled with Rust 1.56.1. I'm pretty sure it worked on the same machine back in September, using Rust 1.55 but on an older version of the OS. (It still crashes when I compile it with Rust 1.55 now.) It does not seem to crash when I replace the global allocator with jemalloc (using the latest version of the jemallocator crate).

It crashes like this:

```
build-history(20530,0x700013b4c000) malloc: *** error for object 0x600680e0c1e0: pointer being realloc'd was not allocated
build-history(20530,0x700013b4c000) malloc: *** set a breakpoint in malloc_error_break to debug
```

I've isolated it to this block of code:

```rust
    data.into_par_iter()
        .fold::<Vec<(Foo, Vec<(BarIndex, Baz)>)>, _, _>(Vec::new, |mut acc, item| {
            let (foo, bar, baz) = item;
            let idx = *map.get(&bar).unwrap();
            match acc.last_mut() {
                Some(last) if last.0 == foo => {
                    last.1.push((idx, baz));
                }
                _ => {
                    acc.push((foo, vec![(idx, baz)]));
                }
            }
            acc
        })
        .reduce(Vec::new, |mut l, r| {
            l.extend(r);
            l.par_sort_unstable_by(|l, r| l.0.cmp(&r.0));
            l.dedup_by(|other, first| {
                if first.0 != other.0 {
                    return false;
                }
                first.1.append(&mut other.1);
                true
            });
            l
        })
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fa555dc6d59e23e04b61650e1764c8c4) with a function and some supporting context.)

I haven't yet been able to actually get the debugger to run but I will be trying that (and would appreciate any hints about what to look at when I do).

**Comment by cuviper** [comment]
Would it be possible to run it under valgrind? That might kill the parallelism needed to actually reproduce the issue, since valgrind serializes threads to run one at a time, but if you find it that should report good details for the error and source.

**Comment by djc** [comment]
valgrind on macOS usually doesn't work well IME. We tried educing the optimization level and/or turning LTO off and it failed in the same way. It seems that something is broken with the macOS 12-provided /usr/lib/libstdc++.6.dylib. Swapping to the homebrew-provided libstdc++ seems to fix the crash, and using link-cplusplus to swap to libc++ also seems to fix the crash. It seems to be similar to the issue discussed [here](https://github.com/ibmdb/python-ibmdb/issues/648#issuecomment-959782632). Switching to jemalloc or mimalloc seemed to fix this.

I'll see if I can provide a standalone reproducer, but I guess the issue is not in rayon anyway. Feel free to close this, though if you have any ideas on how to further debug this that would still be appreciated!

**Comment by igrr** [comment]
Linking to the upstream issue: https://github.com/rust-lang/rust/issues/92173

**Comment by djc** [comment]
Let's just close this in favor of that issue, then.
