### ISSUE TITLE
Blocking I/O with rayon threadpool could lead to deadlock.

### ISSUE THREAD

**Issue by Fomalhauthmj** [rayon-rs/rayon#904]
The closure passed to the threadpool is:
```rust
fn serve(engine: impl KvsEngine, tcp: TcpStream) -> Result<()> {
    let mut r = tcp.try_clone()?;
    let mut reader = Deserializer::from_reader(BufReader::new(&tcp));
    let mut writer = BufWriter::new(&tcp);
    let req = Request::deserialize(&mut reader)?;
    macro_rules! send_resp {
        ($resp:expr) => {{
            let resp = $resp;
            serde_json::to_writer(&mut writer, &resp)?;
            writer.flush()?;
        }};
    }
    match req {
        Request::Get(key) => send_resp!(match engine.get(key) {
            Ok(value) => GetResponse::Ok(value),
            Err(e) => GetResponse::Err(format!("{}", e)),
        }),
        Request::Set(key, value) => send_resp!(match engine.set(key, value) {
            Ok(_) => SetResponse::Ok(()),
            Err(e) => SetResponse::Err(format!("{}", e)),
        }),
        Request::Remove(key) => send_resp!(match engine.remove(key) {
            Ok(_) => RemoveResponse::Ok(()),
            Err(e) => RemoveResponse::Err(format!("{}", e)),
        }),
    };
    let mut buf = Vec::new();
    r.read_to_end(&mut buf)?;
    Ok(())
}
```
This code needs process a request from a TCP connection with a client, and then sends response back.
When client received response, it will shutdown WRITE and exit.
Importantly, the `KvsEngine` is a wrapper about `Arc<Mutex<SharedKvStore>>`, so in `serve()` function it will try to require lock to process request.
 In my benchmark about 1000 concurrent TCP connections with different threadpool, use rayon threadpool sometimes will lead to deadlock at Server Side.
I have tried `install()` and `spawn()` method in rayon threadpool, but it doesn't work.
Does rayon threadpool support this usage? if support, how to use? Thx!

**Comment by cuviper** [comment]
It's not inherently a problem to make blocking calls in the rayon threadpool, but this could introduce deadlocks if the thing that's meant to unblock that is also running in the pool, like #592.
