### ISSUE TITLE
[feature] `FromParallelIterator` for `arrayvec::ArrayVec`

### ISSUE THREAD

**Issue by BartMassey** [rayon-rs/rayon#905]
Would sure be nice to have `rayon::iter::FromParallelIterator` implemented for `ArrayVec` from the `arrayvec` crate. Would the implementation belong in Rayon under a feature gate, or somewhere else? What might make it hard? Should I just try to put together a pull request?

**Comment by cuviper** [comment]
Usually our trait implementations get added as an optional "rayon" feature of the other crate, especially because efficient implementations may need to access private details of the type.

**Comment by BartMassey** [comment]
Thanks much! Filed https://github.com/bluss/arrayvec/issues/209
