### ISSUE TITLE
Documentation for `wasm32-wasi` support?

### ISSUE THREAD

**Issue by saona-raimundo** [rayon-rs/rayon#910]
Hi! Thank you for all the work.

I wanted to ask for documentation to use rayon in `wasm32-wasi` target, like running a wasm module with `wasmtime`.

I have seen documentation for the web like the current link in the readme and others:
- [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon)
- [wasm-bindgen Parallel Raytracing](https://rustwasm.github.io/docs/wasm-bindgen/examples/raytrace.html)

Some issues that are related are #93 and the PR #636.

Maybe I did not read carefully enough but my goal is to:
- Write a Rust program using rayon
- Compile it to `wasm32-wasi`
- Run it with `wasmtime`

If I naively do just this I get the known thread pool not initialized error.

(Maybe I should also ask in wasmtime?)

**Comment by cuviper** [comment]
IMO, it would be better to improve the documentation in one of the wasm-specific repositories, especially since the mechanism is currently experimental and may change as the wasm standard evolves.
