### ISSUE TITLE
Passing MPSC into partition map

### ISSUE THREAD

**Issue by 1Dragoon** [rayon-rs/rayon#916]
I noticed in the documentation that there's a way to pass mpsc handles into into_par_iter().for_each(|f| ...) by using .for_each_with(). Is there a similar analog for passing mpsc handles into into_par_iter().partition_map(|f| ...)?

EDIT: BTW tried something like this:

```rust
        foo.into_par_iter().map_with(tx, |s, x| (s.clone(), x))
        .partition_map(|f: (Sender<u64>, Result<Bar, Error>)| { let tx = f.0; tx.send(...) }
```

Which compiles, but the program ran a bit slower and ultimately dead locks right after the iterator finishes, so that doesn't work. Not using any unsafes or anything like that.

**Comment by cuviper** [comment]
We risk combinatorial explosion if we add every possible variant of every little thing. :)

In this case, I think you could fake `partition_map_with` by putting all of your real code in `map_with` producing an `Either`, and then just use an identity function for `partition_map`.

> ultimately dead locks right after the iterator finishes

How are you running the receiving end?

**Comment by 1Dragoon** [comment]
So I was able to get it to work in the end, but after using that for a while I realized that I would be way better off if I put the main code inside of another function, and have that function return the left/right semantics. Here's my original approach:

https://github.com/1Dragoon/fcp/blob/1e3c50d4c684e9a1355bb7ae9bd7f0d3aee4938e/src/main.rs#L166

I really wasn't happy with that, just so verbose when very few of those lines actually did anything other than error checking/handling. Probably for the best that you guys didn't implement this as it would encourage somebody to create a real mess like I did there :)
