### ISSUE TITLE
Intended implementation of ParallelIterator

### ISSUE THREAD

**Issue by Adamcake** [rayon-rs/rayon#917]
Over at OpenGMK, a game engine project I'm contributing to, we parse data files which are mostly formatted like this:
```
[u32 indicating number of objects]
Then for each object:
    [u32 indicating length]
    [byte stream of that length, compressed with Zlib]
```
So all we need to do to parse an object is read a u32, then read that many bytes into a flate2 decompressor and do some custom stuff with the output, then repeat n times. We have a [custom iterator](https://github.com/OpenGMK/OpenGMK/blob/e025458c359399bbc1172dd86d18188ff79ed629/gmk-parser/src/gmk.rs#L686-L739) which does exactly that.

Now lately I've been tackling the job of parallelizing this with Rayon. It seems I can't implement `ParallelIterator` on this Parser struct because `drive_unindexed()` is based on accessing arbitrary indexes (I think?) and indexing this format would be O(n) - there are sometimes several thousand objects per file so we can't do that.

Instead, the [solution](https://github.com/OpenGMK/OpenGMK/blob/e025458c359399bbc1172dd86d18188ff79ed629/gmk-parser/src/gmk.rs#L741-L785) I came up with was to pre-collect all the slices of compressed data into a `Vec<&[u8]>`, then call `par_iter()` on that Vec. This moves all of the heavy lifting into Rayon's care, which is my primary goal. But it feels like a hack to me - mainly because the heap usage doesn't feel like it should be necessary. Is there a better way of doing this? I've been reading about the producer/consumer/bridge model Rayon uses internally but I can't quite tell whether we could use it to our advantage.

Sorry if this is a lot of info to drop all at once; I hope I've been clear.

**Comment by Lesiuk** [comment]
I had the same issue when processing a huge pgn file, and I solved it the same way.

**Comment by cuviper** [comment]
The chained object lengths make that serial by nature. You could possibly optimize the up-front heap usage by only skimming the lengths up front, seeking past the actual object data to collect your own directory of object offsets in the file. Then in parallel, you can use the unix [`FileExt`](https://doc.rust-lang.org/std/os/unix/fs/trait.FileExt.html) to `read_at` offsets from different threads, without affecting the file cursor. Windows instead has [`FileExt`](https://doc.rust-lang.org/std/os/windows/fs/trait.FileExt.html) `seek_read`, which does affect the cursor -- but maybe that's ok in your case.

As for the general approach, that's a good way to go, implementing the parallel traits based on existing types when possible. I don't think you would gain anything here by trying to implement the "plumbing" yourself.

**Comment by Adamcake** [comment]
Alright thanks. I was mainly wondering if there'd be a way of dividing up the chunks and handing each one to Rayon in one pass. If not then I'll happily continue with my current approach. Thanks for the insight!
