### ISSUE TITLE
segfault during parallel traversal with `jwalk` using `dua`

### ISSUE THREAD

**Issue by Byron** [rayon-rs/rayon#919]
As #738 shows reproducing segfaults isn't an easy task, so I will do my best to make that possible. Please note that I by no means know for sure that `rayon` is the actual cause of it, but it's a guess due to the following

- neither `dua-cli` nor `jwalk` have any `unsafe` code blocks
- running `dua -t1` doesn't segfault by entering an entirely different serial codepath that bypasses `rayon`
- using more threads seems to make it more likely for the issue to occur
- it always traps or panics in `rayon_core::sleep::Sleep::wake_specific_thread`

`rayon` is heavily used by the parallel traversal, along with custom bridges used by `jwalk` , and has many `unsafe` code blocks which make it a candidate to cause the issue.

Since working with Rust I haven't seen any segfaults so I hope with this issue I can help fixing a source of UB in the Rust ecosystem. I hope that the authors of this crate can help to shed some light to resolve the issue here or and help find its origin - I don't know how to investigate further at this point.

### How to reproduce

What follows works for me, knowing very well that segfaults can be illusive. Let's hope this leads to reproductions on other machines to prove its existence.

```bash
# the following takes a while, the download is about 350MB and requires 3.5GB on disk in 570k small files
git clone https://github.com/the-lean-crate/waste
cd waste
# this local state was able to reproduce the issue
git checkout aaf8851d414362b64bd54b753f6e085d40c6c2c1
which dua || cargo install dua-cli
# more threads seem to make the issue more likely to occour
dua -t 10 
```

When running the above, I usually see either a segfault or this, with varying thread indices

```
bash-3.2$ RUST_BACKTRACE=1 dua -t 10
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 9', /Users/byron/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/sleep/mod.rs:355:28
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rayon_core::sleep::Sleep::wake_specific_thread
   4: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   5: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Abort trap: 6
```

```sh
bash-3.2$ RUST_BACKTRACE=full dua -t 10
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', /Users/byron/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/sleep/mod.rs:355:28
stack backtrace:
   0:        0x100859d28 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98d8e939df2a84c8
   1:        0x100835ba8 - core::fmt::write::ha8927896f8d44e8d
   2:        0x100858994 - std::io::Write::write_fmt::h5be52fc0ae77f963
   3:        0x100858fa0 - std::panicking::default_hook::{{closure}}::h7ab34c9d6fd8d067
   4:        0x10085870c - std::panicking::rust_panic_with_hook::h032de7ae9e9d479f
   5:        0x1008805a8 - std::panicking::begin_panic_handler::{{closure}}::ha7b561c0fbbe4ae5
   6:        0x100880518 - std::sys_common::backtrace::__rust_end_short_backtrace::h0ff1db7619f9e51e
   7:        0x1008804e4 - _rust_begin_unwind
   8:        0x100894a90 - core::panicking::panic_fmt::h660aa0926f67c6d3
   9:        0x100894a64 - core::panicking::panic_bounds_check::h3ce336b975d2ef01
  10:        0x10084bf98 - rayon_core::sleep::Sleep::wake_specific_thread::ha6625f56b284407a
  11:        0x1007eab54 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7e4f92f8addc7dc5
  12:        0x1008976a8 - rayon_core::registry::WorkerThread::wait_until_cold::h04855dae27507c1d
  13:        0x10084d3d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hae3d28ef5e686782
  14:        0x10084ccd0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcc2d1e941cc9b09c
  15:        0x100881bd0 - std::sys::unix::thread::Thread::new::thread_start::h8d5e19fc4f27caac
  16:        0x18468d240 - __pthread_deallocate
Abort trap: 6
```

When attaching a debugger, I managed to consistently end up in the same/similar spot: ` rayon_core::sleep::Sleep::wake_specific_thread`:

<img width="1470" alt="Screen Shot 2022-02-21 at 3 34 01 PM" src="https://user-images.githubusercontent.com/63622/154908984-aa31d2a6-250c-4ee7-97c8-0b5d6e475d0b.png">
 
#### Environment

- `dua` v2.17.0 with `rayon-core` v1.9.1
- OS: MacOS 12.2.1, aarch64, 16GB RAM

CC @jessegrosjean as the author of `jwalk`  in case they are interested to follow along

**Comment by jessegrosjean** [comment]
Sorry, I haven't been working in rust lately and don't have time to look into this right now. I would be suspicious of this code in jwalk:

https://github.com/jessegrosjean/jwalk/blob/master/src/core/jwalk_par_bridge.rs

It's a slightly modified version of rayon's par_bridge. It may be that rayons implementation has changed? I'm not sure why that should create a segfault, but anyway that file is where I would look first if you think the problem is coming from jwalk.

Jesse

**Comment by cuviper** [comment]
Unfortunately, I don't have macOS to test myself, and it's not reproducible for me on Linux.

The rayon code in question is safe, here:

https://github.com/rayon-rs/rayon/blob/f45eee8fa49c1646a00f084ca78d362f381f1b65/rayon-core/src/sleep/mod.rs#L354-L357

And the `lock()` call in the standard library will end up here:

https://github.com/rust-lang/rust/blob/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys/unix/mutex.rs#L61-L65

Your crashing `ldr` is right before the actual call to `pthread_mutex_lock`, so I guess that must be part of the argument setup. Maybe `worker_sleep_states` was corrupted, but I don't know how.

**Comment by Byron** [comment]
Thanks for taking a look, too bad it doesn't reproduce on linux.

Maybe it's possible to run it with valgrind and see memory violations that way, out of the back of my head I don't know what the equivalent would be on MacOS to get closer the the origin of the corruption.

Related to the par_bridge trait implementation that `jwalk` modifies from rayon, I would assume that a safe trait can't cause UB even if it was violating some constraints.

It's worth noting that the crashes or panics happen when threads are shutting down.

Possible avenues one could take from here are

- study par_bridge and see how it differs from rayons own implementation. Maybe bring both implementations closer together again to see if that improves something.
- try to run with more instrumentation to see where invalid memory accesses happen to get closer to the source of the corruption.

I will try to make time for looking at the par_bridge.

**Comment by cuviper** [comment]
FWIW, #913 also seems similar, crashing near shutdown in `wake_specific_thread`, although they at least got an out-of-bounds index panic. Yours seems like it might be the same issue but having passed the bounds check. Maybe that's a race somehow with shutting down the threads, destroying data too soon elsewhere, but I'm grasping at straws.

I wouldn't worry too much about `par_bridge` itself -- it's built on the normal iterator "plumbing", which mostly uses `rayon_core::join` for the actual work in the thread pool. It should not be possible for that to get the pool in a bad state.

**Comment by Byron** [comment]
Thanks for linking these issues, I think they are one and the same judging by the location of crash as well.

> […] although they at least got an out-of-bounds index panic. 

I get that too - rarely it panics, most of the time it segfaults. That's good as it clearly points to some memory corruption which seems to sometimes lead to 'lucky' panics.

> I wouldn't worry too much about par_bridge itself -- it's built on the normal iterator "plumbing", which mostly uses rayon_core::join for the actual work in the thread pool. It should not be possible for that to get the pool in a bad state.

Without knowing anything about it, it makes perfect sense to assume that on a technical level. If UB was possible with that trait, it would be `unsafe`. Furthermore, #913 doesn't seem to involve a custom par_bridge at all, so `jwalk` as the cause seems out of the question now.

**Comment by cuviper** [comment]
In #929, it seems their issue involves multiple thread pools, with jobs crossing between -- `in_worker_cross`. Would that be happening in your case as well?

Your backtrace is limited as a release build with no debuginfo, so inlines aren't visible. Could you enable debuginfo so we'll see inlined calls as well? It would also help to see backtraces of *all* threads.

**Comment by Byron** [comment]
The last time I posted a stack trace it was with this patch applied. It's release mode + debug info already and I wonder if that removes inlining or keeps it.

```patch
commit 5b7e0083aff1f95931104c5d1b7ebe1b96aecd22
Author: Sebastian Thiel <sebastian.thiel@icloud.com>
Date:   Sat Apr 2 08:08:15 2022 +0800

    try to reproduce rayon issues with assertions
    
    https://github.com/rayon-rs/rayon/issues/913#issuecomment-1086231137

index f85656a..872453e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -55,6 +55,10 @@ overflow-checks = false
 lto = "fat"
 codegen-units = 1
 build-override = { opt-level = 0 }
+debug-assertions = true 
+
+[patch.crates-io]
+rayon = { path = "/Users/byron/dev/github.com/rayon-rs/rayon" }
 
 [dev-dependencies]
 pretty_assertions = "1.0.0"
```

I ran it again in plain debug mode but it wouldn't reproduce there. Retrying in release mode _didn't_ reproduce it either though. In the mean time, I did get a MacOS update and maybe that affected something. After updating all dependencies and updating my local rayon clone I still couldn't reproduce.

Hence I have to close this issue but will reopen if I encounter it agin.

Thanks for your guidance thus far, if it happens again I will know how to run the program to get the most information for debugging.
