### ISSUE TITLE
[Question] how to pass a name to a thread spawn handler?

### ISSUE THREAD

**Issue by jtmoon79** [rayon-rs/rayon#924]
How do I name a thread created using the `ThreadPoolBuilder`?  More specifically, the documentation does not clarify how to pass the `name` to the thread spawn handler.

[According to the documentation](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPoolBuilder.html#examples-1)

> The default spawn handler sets the name and stack size if given, and propagates any errors from the thread builder.

```lang-rust
fn main() -> Result<(), rayon::ThreadPoolBuildError> {
    let pool = rayon::ThreadPoolBuilder::new()
        .spawn_handler(|thread| {
            let mut b = std::thread::Builder::new();
            if let Some(name) = thread.name() {
                b = b.name(name.to_owned());
            }
            if let Some(stack_size) = thread.stack_size() {
                b = b.stack_size(stack_size);
            }
            b.spawn(|| thread.run())?;
            Ok(())
        })
        .build()?;

    pool.install(|| println!("Hello from my fully custom thread!"));
    Ok(())
}
```

However, it's not clear where `name` would be passed in.

In my case, the names of threads are based on user-supplied command-line arguments. i.e.

```lang-text
$ my_rust_prog a b
```

would result in two threads named `a` and `b`.  Could you describe or demonstrate how to create _n_ number of threads that are named from values determined at runtime?

**Comment by wagnerf42** [comment]
i think you need to use this
https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.thread_name

**Comment by cuviper** [comment]
For example:

```rust
pub fn named_pool(names: Vec<String>) -> Result<ThreadPool, ThreadPoolBuildError> {
    ThreadPoolBuilder::new()
        .num_threads(names.len())
        .thread_name(move |i| names[i].clone())
        .build()
}
```
