### ISSUE TITLE
Can I rely on non-parallel `chain`?

### ISSUE THREAD

**Issue by LoganDark** [rayon-rs/rayon#947]
So I have a blur algorithm that needs to execute both horizontally and vertically. Both the iterators are the same type, so it's possible to iterate over `rows.chain(cols)`, which I do for non-parallel execution.

Now, doing this in parallel would be a mistake because all the rows need to be done before any of the cols can be done, obviously.

Or would it?

Actually, using `rows.chain(cols).par_bridge()...` works just fine! All the rows are executed in parallel and then all the cols are executed in parallel, but they don't mix! Why?

Why are all the rows completing before any of the cols do?

If I do `rows.par_bridge().chain(cols.par_bridge())`, I get flickery race conditions as expected.

But... *why* does non-parallel `chain` act like this? Presumably this is only *accidentally* working as intended, and it's actually a bug in `rayon`, but I honestly have no idea, which is why I ask here.

If this isn't a bug, then it's actually really perfect and beautiful, but if it is, then I should move off of it ASAP... I don't know which it is.

**Comment by LoganDark** [comment]
I just answered my own question. It looks like the only reason using `chain` Happened To Work is because my algorithm is constant-time. The moment I started introducing SIMD iterators (that return leftovers at the end of iteration) I started getting data races again.

**Comment by cuviper** [comment]
The difference is that `rows.chain(cols).par_bridge()` will spread items in parallel as they come out of `rows` first, then `cols`. There will still be _some_ overlap where the last `rows` are running while the first `cols` items start, if it's not timed perfectly.

But with `rows.par_bridge().chain(cols.par_bridge())`, the parallel `chain` will fully split the `rows` and `cols` parts in parallel. It uses `rayon::join` to immediately break those into separate jobs that run independently.
