### ISSUE TITLE
enumerate doesn't satisfy `_: Iterator` for hashmap.par_iter() or hashmap.par_iter_mut()

### ISSUE THREAD

**Issue by ctaoist** [rayon-rs/rayon#949]
## Exmaple

```rust
use rayon; // 1.5.3
use rayon::prelude::*;
use std::collections::HashMap;

fn main() {
  let mut m = HashMap::from([("1", "2")]);
  m.par_iter().enumerate().for_each(|x| {
      println!(":?", x);
  });
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=18ebeb6caf65cbd84be4fed789e83988

## Error

```
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): the method `enumerate` exists for struct `rayon::collections::hash_map::Iter<'_, &str, &str>`, but its trait bounds were not satisfied
  --> src/main.rs:7:16
   |
7  |   m.par_iter().enumerate().for_each(|x| {
   |                ^^^^^^^^^ method cannot be called on `rayon::collections::hash_map::Iter<'_, &str, &str>` due to unsatisfied trait bounds
   |
  ::: /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/collections/hash_map.rs:32:1
   |
32 | pub struct Iter<'a, K: Hash + Eq + Sync, V: Sync> {
   | ------------------------------------------------- doesn't satisfy `_: Iterator`
   |
   = note: the following trait bounds were not satisfied:
           `rayon::collections::hash_map::Iter<'_, &str, &str>: Iterator`
           which is required by `&mut rayon::collections::hash_map::Iter<'_, &str, &str>: Iterator`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error
```

**Comment by wagnerf42** [comment]
what is the order you expect ?

iterating on hash tables gives in sequential is done in a non deterministic order.
it is not possible to enumerate it in parallel without some overhead and this means that the hash table parallel iterator is not [indexed](https://docs.rs/rayon/latest/rayon/iter/trait.IndexedParallelIterator.html).

if you really want to enumerate you need to either collect into a vec and use a parallel iterator on the vec or use a sequential iterator, enumerate and use [par_bridge](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelBridge.html#tymethod.par_bridge).
in both cases you'll pay some extra cost.

i'd advise you to reconsider why you need it.

**Comment by ctaoist** [comment]
I am sorry that I've forgotten that hashmap is not ordered.

Thanks a lot!
