### ISSUE TITLE
Deterministically reproducible monte carlo simulation using Rayon?

### ISSUE THREAD

**Issue by masonk** [rayon-rs/rayon#954]
I'm trying to understand if it's possible to write a monte carlo simulation in Rayon that produces deterministic output. I currently think it's not possible, but I'd like your authoritative answer.

https://github.com/rust-random/rand/pull/399#issuecomment-1175104559 (related thread)

I can control the seeds that are used by each Rayon batch using `map_init`, but:

1. I can't directly control the number of batches that will be spawned (is this guaranteed to == # threads in the current threadpool? Because I think I have seen examples where there are actually many more batches than threads).

2. I can't stop threads from stealing work nondeterministically, and when that happens some items get processed using a different seed.

**Comment by adamreichold** [comment]
(Maybe just to complete the picture: Work-stealing does work though, i.e. load balancing could be rather bad with the spatial work distribution if the number of interactions per region differed significantly due to the simulation setup (heterogeneous landscapes in our case.))

**Comment by adamreichold** [comment]
>  Even calling rand::thread_local() from the hot function adds 25% to my wall time, and that's pretty cheap.

I think the general purpose thread-local PRNG is relatively expensive compared to a cheap small PRNG like PCG64 from `rand_pcg` with per-item state. And the seeding will happen only during initialisation.
