### ISSUE TITLE
Execute jobs on thread pool in parallel with main thread

### ISSUE THREAD

**Issue by akhvoshch** [rayon-rs/rayon#961]
`rayon` allows to execute two closures simultaneously (via `join`) or more (via `scope`). This is fine for most cases. However, it's not possible to use `join` or `scope` with non-`Send` closures.
Implementing `Send` for a closure isn't always possible. Some external APIs/modules requires execution on specific thread (OpenGL, WinAPI, etc.).

But if closure doesn't implement `Send` it is still possible to execute it in caller (main) thread while executing other closure(s) on thread pool. I suggest to implement method(s) that allow to execute some code on caller thread and some on thread pool. First, add function like `join_in_place` as alternative for `join` that requires `Send` only for one of arguments. Second, add analog of `scope` function with additional parameter for closure that will be executed while waiting of completion of jobs spawned within this scope.

**Comment by cuviper** [comment]
> I suggest to implement method(s) that allow to execute some code on caller thread and some on thread pool.

One wrinkle we also have to deal with in general is that the caller thread might also be part of a thread pool, maybe even a different pool than the one you're sending to. This is not necessarily a problem, it just means in that case that we should participate in work-stealing while waiting for the sent parts to complete.

> First, add function like `join_in_place` as alternative for `join` that requires `Send` only for one of arguments.

Sure, we discussed something like that way back in #20, but never pursued it. If there's a real need, I think it wouldn't be hard.

> Second, add analog of `scope` function with additional parameter for closure that will be executed while waiting of completion of jobs spawned within this scope.

We already have `scope_in_place` -- that can `spawn` and then do whatever other work you want before returning. Do you mean something different?

**Comment by akhvoshch** [comment]
> We already have scope_in_place

It seems to be what I need. And it is more flexible than hypothetical `join_in_place`.

**Comment by cuviper** [comment]
(You probably figured it out, but I meant [`in_place_scope`](https://docs.rs/rayon/latest/rayon/fn.in_place_scope.html).)
