### ISSUE TITLE
Rayon citation

### ISSUE THREAD

**Issue by 2pt0** [rayon-rs/rayon#984]
Sorry to clog up issues with this question, but I am unsure of where else to ask this.

I am using `rayon` for a research project and would like to cite `rayon` for its great benefit in seamlessly parallelizing my research code. Is there a desired way to cite `rayon` in my paper(s)?

Thanks!

**Comment by nikomatsakis** [comment]
I think that citing the github repository along with "Rayon developers" would be appropriate.
