### ISSUE TITLE
rayon-demo bench doesn't build

### ISSUE THREAD

**Issue by dcompiler** [rayon-rs/rayon#994]
Compiling on a MacBook Air running Mac OS 12.5: 

rayon-demo % cargo bench                     
   Compiling rayon-demo v0.0.0 (/.../rayon/rayon-demo)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> rayon-demo/src/main.rs:1:27
  |
1 | #![cfg_attr(test, feature(test))]
  |                           ^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `rayon-demo` due to previous error

**Comment by cuviper** [comment]
That's expected, they're written with the still-unstable `#[bench]` attribute.

**Comment by dcompiler** [comment]
Thanks.  BTW I just got it to run with "rustup run nightly cargo bench"
